### ISSUE TITLE
404 errors for MaterialIcons

### ISSUE THREAD

**Issue by rad-pat** [qooxdoo/qooxdoo#10029]
Having compiled from latest source and compiler, since the tangible theme was merged, we see 404 errors for MaterialIcons. We haven't changed to use the new themes ourselves

**To Reproduce**
Create new Qooxdoo Application and run, observe 404 errors in browser console.
`qx create myapp --type desktop --noninteractive --out=.`

**Comment by oetiker** [comment]
I could not reproduce that particular problem, still the MaterialIcons and the Tangible themes can not be used, because in the npm @qooxdoo/framework package the file https://github.com/qooxdoo/qooxdoo/blob/master/framework/Manifest.json is missing or rather instead of this file, it seems that the file https://github.com/qooxdoo/qooxdoo/blob/master/Manifest.json which is unfortunate as the master/Manifest is missing all the interesting bits to get the IconFonts working.

**Comment by oetiker** [comment]
@johnspackman or @hkollmann can you help

**Comment by hkollmann** [comment]
@rad-pat : Could you test this issue again? Thanks a lot.

**Comment by rad-pat** [comment]
@hkollmann I can still observe the 404s with both my application and with a newly generated application using `@qooxdoo/compiler    v1.0.0-beta-20200928-1855` and Qooxdoo at `c446bb56ccdd41c3c25887f7b89ff3250e4717c8`

**Comment by rad-pat** [comment]
I no longer get 404s for the MaterialIcons.
