### ISSUE TITLE
Qooxdoo's cookie handling needs to be updated to use modern standards

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#10050]
Firefox emits "Cookie 'cookie name' will be soon treated as cross-site cookie against 'file' because the scheme does not match" in the console. Other browser vendors might follow.

We need to update [`qx.bom.Cookie`](https://qooxdoo.org/qxl.apiviewer/#qx.bom.Cookie) in order to avoid to break our apps in Firefox (and elsewhere) as soon as this policy is implemented.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by hkollmann** [comment]
@cboulanger I can’t reproduce this on http://qooxdoo.org/qxl.demobrowser/ or https://qooxdoo.org/qxl.apiviewer/ ? The fix is that cookies must contain SameSite=Strict or SameSite=None - this is already supported by qx.bom.Cookie.set, but by default SameSite is ignored. The fix would be to set SameSite=Strict by default, and possibly also Secure
