### ISSUE TITLE
COMPILER: Avoid download of packages not used by main application

### ISSUE THREAD

**Issue by adrelino** [qooxdoo/qooxdoo#10187]
**Describe the bug**
When the `Manifest.json` of a package contains a dependency that is not used by the main application using that package, it is nevertheless downloaded.

**To Reproduce**
in package:
```
  "requires": {
    "qooxdoo/qxl.apiviewer": "^1.0.18",
    "@qooxdoo/framework": "^6.0.0",
    "@qooxdoo/compiler": "^1.0.0"
  }
 ```

**Expected behavior**
The main application only downlods the packages it needs, but not the packages that demo applications of packages may need.

**Additional context**
It is useless but of no harm, can be avoided inside the package with `npx qx package install qooxdoo/qxl.apiviewer --save=0`, which only saves the apiviewer dependency in `qx-lock.json` but not in `Manifest.json`

**Comment by cboulanger** [comment]
One solution would be to switch the default of the `save` CLI argument to "0". If you want to make a dependency "sticky", you would need to add `--save` explicitly. I tend to think that this makes sense, since the dependency is saved in `qx-lock.json` in any case so that `qx pkg install` (with no arguments) will keep working to install all dependencies, but `Manifest.json` will be left alone.

**Comment by hkollmann** [comment]
Changed default value to false
