### ISSUE TITLE
qx es6ify bugs

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#10330]
1. .prettierignore is ignored.

reproduce:

run qx es6ify . in qooxdoo root.

/bin/ is processed.

2. parameter  exclude is not handled as array:
   if (exclude && filename.startsWith(exclude)) {

**Comment by johnspackman** [comment]
Also the ex lint no longer understands our syntax because we misuse super()

What do you mean about 2.? I don't understand

**Comment by hkollmann** [comment]
Parameter description says that it is type array. Handling is done as single string

**Comment by hkollmann** [comment]
> Also the ex lint no longer understands our syntax because we misuse super()
> 
> What do you mean about 2.? I don't understand 

Could be handled by an eslint rule, could'nt it?

**Comment by johnspackman** [comment]
Possibly, the reason it exists is because it is possible to provide paths on the command line which are inclusion, so exclude is supposed to balance that

**Comment by johnspackman** [comment]
>>Also the ex lint no longer understands our syntax because we misuse super()
>Could be handled by an eslint rule, could'nt it?

no, the problem is that the underlying babel parser sees `super` and rejects it because it is not in an es6 `class` so is illegal; the solution is to produce a custom eslint parser, based on the babel eslint parser, which turns on the switch to tell babel to allow super anywhere.  I had the same problem in es6ify, the fix was this one line: https://github.com/qooxdoo/qooxdoo/blob/master/source/class/qx/tool/compiler/Es6ify.js#L161
