### ISSUE TITLE
const ol = require("ol") gives exception

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#10398]
**Describe the bug**
import do not work for ol

**To Reproduce**
1. unpack attached test project
2. run npm install
3.  run npx qx compile

See exception:

Failed: Error: Parsing file D:\Projekte\github.windows\qooxdoo\test\node_modules\ol\index.js: 'import' and 'export' may only appear at the top level (5:0)

[test.zip](https://github.com/qooxdoo/qooxdoo/files/8710925/test.zip)

**Comment by derrell** [comment]
Yes, this is the same problem @sknick was having with `require("jose")`. I have been unable to find any `browserify` options that allow bundling node modules (in `node_modules` directory) that are implemented as as ES6 modules, although the `localModules` ES6 module tests worked fine. I'm happy to receive assistance finding options that work. (It fails even when using `browserify` from the command line, so it's not qooxdoo-specific. There *must* be some options that can make it work...

**Comment by johnspackman** [comment]
AIUI the problem is that imports have to be at the top of the file, but when we transpile the code we add wrappers and other stuff which means that the imports are not at the top of the file any more.

This means that we would have to hoist the import declarations to the top of the file, along with the variables that hold those imported symbols as global to that file.  

This will be a problem because we merge files (eg bundling in source target, with parts, or build target) so therefore we will not know until very late in the compilation process (the compiler's equivalent of "linking", to use a C analogy) what goes at the top and therefore we would have to cater with name conflicts.  This would be possible if we remapped the imported symbols in each source file.

IMHO this would be hard work.  

A much simpler alternative would be to implement `import` as though `import` is simply not supported, ie remap `import` into `require` - this would solve the problem with browsers complaining about where the import is, but I dont know if this would break any functionality.  There is precedence for this, because babel supports that for older JS

EG https://www.npmjs.com/package/babel-plugin-import

**Comment by derrell** [comment]
That was just the hint I needed. Using browserify plugin `https://github.com/mattdesl/esmify` solves the problem and applies only to `@require` without otherwise affecting the overall qooxdoo compilation. PR forthcoming.

**Comment by hkollmann** [comment]
Are you working on it? I found the solution yesterday evening using babelify.
I could do the pr if you like!

**Comment by derrell** [comment]
Sure. I'll compare what you did with what I did. Likely very similar. Go ahead and publish a PR.
