### ISSUE TITLE
Add more modern theme 

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#211]
It miss a modern theme/icons for qooxdoo (ie flat theme). 
This example seems to be the best candidate for that : http://sqville.com/examples/qxthemes/clean/index.html

**Comment by johnspackman** [comment]
+1

**Comment by oetiker** [comment]
@johnspackman you can just click on the little face on the issue itself to +1 it

**Comment by johnspackman** [comment]
aha :)

**Comment by slachtar** [comment]
The guys at wisej.com provide a very nice theme builder and there's very nice flat themes as examples.

**Comment by johnspackman** [comment]
is it possible to build a theme that is reusable independent of the wisej api?

**Comment by slachtar** [comment]
the theme builder generates a .theme file which is a json file with all
qooxdoo theme entries (fonts, images, colors, apperances).
I've to test it first.

On Fri, Apr 29, 2016 at 3:40 PM, John Spackman <notifications@github.com>
wrote:

> is it possible to build a theme that is reusable independent of the wisej
> api?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/qooxdoo/qooxdoo/issues/211#issuecomment-215739742>
>



-- 
Slah Lachtar
Tel. (+216) 98 221 575

**Comment by iceteagroup** [comment]
Hi, I just saw this.

We (iceteagroup) will be happy to contribute back to the qooxdoo community both the theme builder and the theme roller classes.

The theme builder is a .NET executable that we can modify to work without wisej. But can make the exe available for free. 

The "theme roller" javascript classes can be added to qooxdoo or provided as an addition. They take the theme json file and convert it to qooxdoo theme classes.

However, I don't know how we can contribute. Maybe we will simply make those available on our website.

**Comment by iceteagroup** [comment]
Oh, forgot to add that we can also contribute all the themes we designed.

**Comment by level420** [comment]
@iceteagroup That would be great! 
Regarding the contributions: please  set your contribution under the MIT license and use the following text passage in the header for this:

```
   License:
     MIT: https://opensource.org/licenses/MIT
```

qooxdoo will change to MIT license soon.

**Comment by oetiker** [comment]
now the real kicker would be if the theme builder was written in qooxdoo ... seems a bit odd that this is in .NET ...

**Comment by level420** [comment]
@oetiker yes, but having the wisej theme builder is about 1000% better than having at the moment ... well ... nothing!

**Comment by oetiker** [comment]
@level420 sure ... I did not want to discurrage @iceteagroup  :) please contribute!

**Comment by johnspackman** [comment]
@iceteagroup this would be a great addition, thank you very much!

**Comment by iceteagroup** [comment]
Ok for the MIT header. But I still have quite a few questions:

- shall we keep the wisej.themeRoller.ThemeRoller  class name or change it to qx.themes.themeRoller...?

- where do I upload the js code?

- the themes work with any image, but all the themes we designed now use svg images, which require some enhacements to the ImageLoader. How to proceed in that case?

- some cool features of the themes require new decorators we added to qooxdoo to handle custom css, transformations, few bug fixes, etc. same question as above.

If there is a link I'll be happy to RTFM :)

The theme builder can be rewritten in qooxdoo, I can't do it, but it's a relatively easy tree based editor of simple json properties. Most of the work is done in the themeroller js class. I can split the .NET cose into a qooxdoo-only version and make the exe available, either on our website or?

Sorry for all the questions. I'm very interested in getting involved but am a neewbe.

Best,
Luca

**Comment by oetiker** [comment]
Hi Luca,

If I understand correctly, the ThemeRoller converts your json description into a proper qooxdoo theme, right ? In that case it is an application and should live under

`https://github.com/qooxdoo/qooxdoo/tree/master/application/themeroller`

so to 'upload' you fork qooxdoo on github, clone it to your local drive, then you branch it, add your files, make sure it builds, commit and then you push it back on to github and finally create a Pull Request.

For the enhancements to the image loader I would create a separate branch first and create a separate pull request. @cajus has been working on the image loader to handle font icons, so he might have some input on the design of your proposed enhancement.

There is no qooxdoo specific documentation yet ... but we try to stick with the regular processes established in the field ... 

For the .NET part, if you could do the split and publish the source too than we could add it to the tree for now as is and then work on converting it to qx ... if you would like to host the exe and thus get some traffic sent your way ... that would be fine ... but we can also just put it up for download from here ... as you like ...

you may also want to get back on https://gitter.im/qooxdoo/qooxdoo for short question answer things that is very handy ... 

thanks a lot for your effort!

**Comment by iceteagroup** [comment]
Not an app. It converts at runtime, like the qx properties. And the resulting theme uses style classes part of the themeroller system.

**Comment by oetiker** [comment]
ah :) in that case `qx.theme.themeroller` might be appropriate I guess once we have the PR for review, you will see much more helpful comments ... at the moment it is all a bit theoretical ...

**Comment by cajus** [comment]
@iceteagroup We added SVG support for qx.ui.basic.Image some time ago. What features are missing for your implementation?

**Comment by iceteagroup** [comment]
I didn't see specific code for svg. They are supported as img or background img sources as any png. This is what we added:

- Change the fill color dynamically using the text color. Otherwise most svg icons are black or white.

- Support for svg embedded base64. It needs to cache the svg as an xml element to adapt the svg to the state (selected, disabled, etc).

- Decorator to support a fillColor style for svg used as background-image.

- Use an hash for the cache in the image loader instead of the source, otherwise you end up having the base64 string as the value and the key.




-

**Comment by cajus** [comment]
Just wondering why you don't see specific code. It should be at least in the latest 5.x release. What we did is adapting the generator to inspect SVGs, extract the (default) sizes and make them managed by the resource manager as all the other images. They're loaded as ordinary images - no inline object/svg. Note that these have no generator sprite support.

Your changes seem to add some more features (like fill color, etc.) for SVGs. So it would be nice to see a PR there.

Alternatively, there's work going on in the cajus/qooxdoo *fonts* branch, with support for icon fonts via the *source* property. It has support for setting the icon color, too. It has no support for background images/decorators yet, since it focuses on qx.ui.basic.Image for now. As a result we could just compile a bunch of SVGs into a single (small) font file and access all the icons there which keeps the HTTP requests low.

**Comment by iceteagroup** [comment]
The generator means the python build tool? We don't use it. The qx framework in Wisej is built in visual studio and minified as part of the build into an embedded resource. It has a global main, similar to sencha extjs (this way we can use it in jfiddle as well). All the theme images are defined in the json theme file.

I just looked again in our qx base (which is 5.1) in qx.ui.basic.Image.js but can't see svg specific code. When I tried to use an svg icon file I get the large icon 254x254 black. Using an svg image as a png as the src of an img element is supported by most browsers now, but that's not enough for svg icons.

Font icons are certainly a great and needed addition, but quite different from supporting svg icon files directly. We can't use font-icons because of several reasons: 1) they are slow to load and hard to sync breaking our designer - sometimes they simply don't appear in IE, 2) for a LOB app you end up needing icons that are not available in a specific font set and we can't ask developers to create a font (or multiple fonts) to add icons, 3) cannot be used as background images which is needed in several layout cases. 4) it "burns" the pseudo before or after that we need in some cases for dynamic themes like google material.

Basically the requirement is simply to be able to use a base64,  a url, or a theme image name as the source of any qooxdoo widget using an image (inline or background) without any additional work.  The assigned image, if it's an svg, dynamically adapt the color to the textColor or fillColor, which may also be controlled by the theme. This way instead of having to define several pngs for the same icon, the same icon is good for all the states. This has simplified the creation of themes enormously.

Since the original xml is cached once, there is no need to request several variations, the color changes are applied on the xml dynamically without any additional request. And since most of the icons are defined as base64 in the json theme file, they are all loaded in a single request, like a font, but without the installation process. Making it possible to add icons at runtime (not known at build time), which is difficult if you need to install a new font to load an icon while the app runs,

There are other issues that are resolved, like removing the width/height elements to let icons resize dynamically (some svg icons lock the size), fixes to the background size and position (different between IE and chrome), etc.

I will start providing all the qx related source code + the .NET source code for the qx build and the theme builder in the next few days.

**Comment by iceteagroup** [comment]
Tried in the playground as well:

http://demo.qooxdoo.org/devel/playground/#%7B%22code%22%3A%22%252F%252F%2520Create%2520a%2520button%250Avar%2520button1%2520%253D%2520new%2520qx.ui.form.Button(%2522First%2520Button%2522%252C%2520%2522https%253A%252F%252Fcommons.wikimedia.org%252Fwiki%252FFile%25253ASitemap_font_awesome.svg%2522)%253B%250A%250A%250A%252F%252F%2520Document%2520is%2520the%2520application%2520root%250Avar%2520doc%2520%253D%2520this.getRoot()%253B%250A%250A%252F%252F%2520Add%2520button%2520to%2520document%2520at%2520fixed%2520coordinates%250Adoc.add(button1%252C%250A%257B%250A%2520%2520left%2520%253A%2520100%252C%250A%2520%2520top%2520%2520%253A%252050%250A%257D)%253B%250A%250A%252F%252F%2520Add%2520an%2520event%2520listener%250Abutton1.addListener(%2522execute%2522%252C%2520function(e)%2520%257B%250A%2520%2520alert(%2522Hello%2520World!%2522)%253B%250A%257D)%253B%22%2C%20%22mode%22%3A%22ria%22%7D

**Comment by level420** [comment]
@iceteagroup do your changes to qx.ui.basic.Image break compatibility in some way? 

Regarding you playground example: would you mind using the shortening URL mechanism of the playground?

**Comment by iceteagroup** [comment]
Yes, sorry about the long url.

No breaks. The changes kick in only for svg urls or base64.

**Comment by cajus** [comment]
Hmm. If you don't use the generator, you've the problem that you'll probably have no proper image handling because all images are "unmanaged" - which might be a bad idea. https://github.com/qooxdoo/qooxdoo/pull/114 contains the changes made to the generator that enable us to use SVG images out of the box. There's no change needed for the qx.ui.basic.Image class to display SVGs. A generator run is needed though.

> 1) they are slow to load and hard to sync breaking our designer - sometimes they simply don't appear in IE

I can't follow here. IE needs EOT files to load. It's neither slow nor do I see any problems on a large application that makes 100% use of font characters. The opposite was the case. Loading time and render time drastically decreased after switching from SVG images.

> 2) for a LOB app you end up needing icons that are not available in a specific font set and we can't ask developers to create a font (or multiple fonts) to add icons

That's why there's a little python script that generates you a font from your SVGs.

> 3) cannot be used as background images which is needed in several layout cases.

This can be achieved with :after if needed.

> 4) it "burns" the pseudo before or after that we need in some cases for dynamic themes like google material.

If you need these. Yes. I personally don't like these dynamical thingies. People are waiting for animations to eat up their CPUs, and while I agree that they look fancy from time to time, they're getting boring after I've seen them ten times. But that's a matter of taste which changes from person to person.

**Comment by level420** [comment]
Then it would be nice to see a PR with your changes to qx.ui.basic.Image. Could you do that?

**Comment by iceteagroup** [comment]
Sure.

**Comment by level420** [comment]
Just a side note: if you create pull requests with new files, please make sure that the license in the file header is the MIT license (not the EPL/LPGP license as before), and if appropriate please add some tests in framework/source/class/qx/test for the new functionality.
Your PR will then run automatic tests via travis.

**Comment by level420** [comment]
License like:
```
   License:
     MIT: https://opensource.org/licenses/MIT
     See the LICENSE file in the project's top-level directory for details.
```

**Comment by cajus** [comment]
@iceteagroup for your example:

```
001513 ImageLoader: Not recognized format of external image 'https://commons.wikimedia.org/wiki/File%3ASitemap_font_awesome.svg'
```

That's what I meant with the resource manager. If you're using the SVG images without using the generator, you can't load them. There's no meta information available to feed the layout manager accordingly. Only managed SVG images are supported.

**Comment by iceteagroup** [comment]
@cajus Look guys, I'm grateful for the quality and everything else in qooxdoo. It's the base of our product selected almost 2 years ago and I love it. I can't use it as an application framework, I need it as a javascript library like sencha extjs. If you don't want to use our code I'm very fine with it. I'm happy to contribute anyway even if it ends up in the recycle bin. I can't argue about stuff that I personally tested and happen to be different from what you tested. Font icons are great, I use them in wordpress sites all the times. I simply cannot use them in web applications because of the many reasons I listed above.

**Comment by cajus** [comment]
@iceteagroup that's completely ok. No one says that we don't want to use your code. I only stated that I made other experiences with SVG. That's all fine. And as I wrote, your PR could be a great addition.

**Comment by level420** [comment]
@iceteagroup There are different ways on achieving what we want to have and it would be great to have all common functionality in qooxdoo and let from there everyone the freedom to use it in different ways.
It would be great to have parts of your work contributed to the framework.

This is only discussion and at some point discussion reveal different points of view.

But all this is not intended to offend you.
You are really welcome!

**Comment by iceteagroup** [comment]
I'm not offended at all! :) Really. We can discuss all you like, but it would end up having to build real test cases and me writing boring pages and pages of stuff. Which is something I'm willing to do if I'm on a customer project, another thing I try to avoid now, after 30+ years of development...

**Comment by johnspackman** [comment]
Am I right in thinking that what @cajus is saying is that the current qooxdoo master is unable to load svg images as decoration because they are unmanaged, but @iceteagroup you're saying that you have a fix for this already?  That sounds good to me ...

**Comment by iceteagroup** [comment]
@johnspackman I guess you are right. I'm not familiar with the pyhton build tools since we use qooxdoo as a javascript prebuilt framework similar to a sencha extjs or kendo ui.

**Comment by iceteagroup** [comment]
Equivalent in jfiddle https://jsfiddle.net/6tL57gk8/

This one can set the color of the icon directly, or setting the button color, or in a theme. It can use icons with more than one color (not supported in icon fonts).

**Comment by cajus** [comment]
@johnspackman not really. Some SVGs have issues that make it hard for qx to be used. I.e. when the SVG has relative size in the document. That's the case for the WIKI example above. Additionally, it brings no own color and draws the path with "currentColor". As long as there is no way to influence the current color in qx, it is more or less useless. So, if your SVGs meet some conditions, you can use them unmanaged of course. The generator can fix the sizing issues. But it cannot fix the color issues.

Currently SVGs are displayed "as they are" - like ordinary images.

**Comment by johnspackman** [comment]
ah ok; also, I realised later last night that the error message is confusing because it's `qx.bom.element.Decoration` saying that the image loader does not know the file format, but it actually only cares about file format when it's a PNG and the browser is IE6/7/8 so that it can do the alpha transparency fix.

**Comment by iceteagroup** [comment]
@level420 to follow up on the PR, @johnspackman has graciously agreed to help us contribute to qooxdoo. Our wisej release date is approaching fast and my lack of familiarity with the contribution process would just create more issues. We have already created a qooxdoo-contrubution SVN repo on our server where I placed all the qooxdoo related code and theme builder source code and shared it already with John. We will work together to create a priority list of fixes, enhancements, new features, etc.

The .NET source code for the theme builder will remain proprietary. However, we can provide a free exe redistribution license assigned to the qooxdoo foundation and a "source sharing" license as well. If other qooxdoo contributors would like to have access to the code please contact @johnspackman or me.

**Comment by level420** [comment]
I want to bring up this two github repos which host themes which seem to be oriented on material design:

1. https://github.com/adeliz/material
2. https://github.com/Estandarte/QxMaterial

The first also has a demo:
http://adeliz.github.io/material/

**Comment by woprandi** [comment]
It's pretty clean, I think not much work is needed from Indigo to have great modern (flat) theme.

**Comment by adeliz** [comment]
@level420 Unfortunatly, https://github.com/adeliz/material is only a clone of the CLEAN theme from sqville. I only tried to extend it to some other qooxdoo widgets and to get familiar with qooxdoo theming.

When I saw that we could expect much more from Iceteagroup, I didn't go further... I hope we'll be able to see more soon!

**Comment by julian-w** [comment]
Anything new on this topic?

I can find some .theme files on the website of wisej, but no code to load the theme into qooxdoo or a theme editor.

**Comment by oetiker** [comment]
unfortunately now ... got any spare hacking time ?

**Comment by sqville** [comment]
.... a year later. :-) 
Hi everyone. I just completed the widgetbrowser version of Clean (http://sqville.com/examples/widgetbrowser2018/index.html). There are a couple of oddities that I need to figure out (widgetbrowser prioritizes "qx-abstract-field" over "qx-inset" for some reason, so my textfields are missing borders; Also, Theme switching is not working. My decorators seem to be sticking). So I would like to submit (PR) the theme within the week. Need the community's help/input on the two oddities just mentioned, and testing my theme for completeness. Here's hoping this works :-)

**Comment by cboulanger** [comment]
We have two new themes now - the Material theme shipped with the framework and the Clean theme as a package. Closing.
