### ISSUE TITLE
setCommand() breaks themed button icon (BZ#5906)


### ISSUE THREAD

**Issue by qx-bug-importer** [qooxdoo/qooxdoo#5974]
_Mustafa Sak (@msak) wrote:_

On buttons with themed icon property, setting of command set icon property to null, so no icon is see able anymore.

_assigned to Martin Wittemann (@wittemann)_

**Comment by cajus** [comment]
The fix involved with this bug opens another bug:

If you've a child control consisting of a *qx.ui.form.Button* which is initialized with a *Command*, this control will never get the correct appearance until you call *updateAppearance* manually.

The problem is caused by the *Command* calling *syncAppearance()* _before_ the child control is completely created. That causes the widget appearance to be initialized too early.
