### ISSUE TITLE
Enable strict mode

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#9000]
Javascript strict mode should be enabled as often as possible in the qooxdoo code.

**Comment by johnspackman** [comment]
I think we're pretty much there with this - qxcompiler enables strict mode on all files, because it's a requirement of babel for ES6.  Already merged are my patches for detecting strict mode where necessary (eg qooxdoo sometimes sets properties on DOM elements to normalise them, probably for IE6 compatibility, but that causes an exception in strict mode etc)

**Comment by cajus** [comment]
@johnspackman is it an enhancement, or isn't it needed because of your comment? If it is not needed because strict mode is globally enabled anyway, can we close it?

**Comment by johnspackman** [comment]
Yes, closing because strict mode support is already incorporated, but just not turned on automatically (unless you use qxcompiler)
