### ISSUE TITLE
Enhance qx.bom.request.Xhr

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#9017]
Hello,

there are some missing items of qx.bom.request.Xhr:

-  Support of native Response
- Support of setting the responseType 

With this you can handle binary data with qx.bom.request.Xhr direct.

best regards,
Henner Kollmann

**Comment by oetiker** [comment]
Hi @hkollmann do you have a Pull Request for us in store ?

**Comment by hkollmann** [comment]
Not yet - i should start learning to work with git. I just tried to use qx.bom.request.Xhr with binary data. It's possible to use the request object with getRequest - but that's not the qooxdoo way.

One question before i start the implemtation:
In native Xhr the responseType ist just a variable of the object. Qooxdoo uses propertys with getter and setter.

So what's to use in qx.bom.request.Xhr? Because responseText, responseXML are handeled the native way i would prefer this.

**Comment by oetiker** [comment]
Look at the implementation in https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/bom/request/Xhr.js it does not use the qooxdoo setters and getters mechanism ... qooxdoo classes must hide away any differences occurring due to browser differences and provide a stable interfaces ... in that way, if there are browser changes, we often just have to fix the relevant classes which makes all the applications built on top of qooxdoo work again.

**Comment by hkollmann** [comment]
Tried a pull request. My first work with git. Hopefully everything is correct.... #9018

**Comment by level420** [comment]
fixed with https://github.com/qooxdoo/qooxdoo/pull/9018

**Comment by hkollmann** [comment]
Changes are commited! Thank you!
