### ISSUE TITLE
Qooxdoo object-contruction

### ISSUE THREAD

**Issue by gernotpokorny** [qooxdoo/qooxdoo#9144]
Hello,
I'm not very satisfied with how object-construction in qooxdoo works. Let me explain. Here is some C++ code.

```
#include "baseclass.h"
#include <QDebug>

BaseClass::BaseClass()
{
    myFunc();
}

void BaseClass::myFunc()
{
    qDebug() << "base";
}
```

```
#include "derived.h"
#include <QDebug>

Derived::Derived()
{
    myFunc();
}

void Derived::myFunc()
{
    qDebug() << "derived";
}
```

`derived = new Derived;`

The output is:

```
base
derived
```

If i do the same thing in qooxdoo, the output is

```
derived
derived
```

Here is the equivalent qooxdoo-code.

```
qx.Class.define("oopissue.BaseClass",
{
  extend : qx.ui.container.Composite,

  construct : function()
  {
    this.base(arguments, new qx.ui.layout.VBox);

    this.myFunc();                   // works not
  },

  members :
  {
    myFunc: function () 
    {
        console.log("base");
    }
  }
});
```

```
qx.Class.define("oopissue.DerivedClass",
{
  extend : oopissue.BaseClass,

  construct : function()
  {
    this.base(arguments, new qx.ui.layout.VBox);

    this.myFunc();                   // works not
  },

  members :
  {
    myFunc: function () 
    {
        console.log("derived");
    }
  }
});
```

`var derivedClass = new oopissue.DerivedClass;`

So why is this a problem, it works in php and java the same way like in qx?

It is a problem, cause it's very error-prone in my opinion. If you define a method with the same name in the base-class and in the derived-class and are not aware that the method has the same name, you run the website and it does stuff you don't want. And now find that mistake.

I'm fine with the function overwriting when the object is created, but during object-contruction it makes no sense to me. I cannot imagine a usecase during object-construction. 

It's also not possible if I want my code to behave like the c++ quivalent to achieve that without naming functions different in my base- and derived-class, which is a really bad workaround. I need that behaviour of the c++-equivalent very often and have really problems to code in qooxdoo now.

The reason why i file this issue is that i hope someone thinks that this is a problem or a nice feature to additionally have in qx, that qx also can behave like c++ during object-construction if desired. I think I cannot code it myself.

Thanky you for reading

**Comment by trupljan** [comment]
That behavior is correct and C++ is wrong. Actually what you described leads to need of two-phase constructor in C++ where you can't call virtual method in constructor as it won't call derived method because vtbl is not yet fully initialized...

To solve your problem with overriding, there could be an error in source version that you are overriding already defined method. There could be another field in class definition called override with a list of overriden members to disable the error.

```
qx.Class.define("oopissue.DerivedClass",
{
  extend : oopissue.BaseClass,

  construct : function()
  {
    this.base(arguments, new qx.ui.layout.VBox);

    this.myFunc();  
  },

 override: ["myFunc"], // if not in list, it would cause an error

  members :
  {
    myFunc: function () 
    {
        console.log("derived");
    }
  }
});
```

alternatively override could serve as a section (is the idea worse or better than previous?):

```
qx.Class.define("oopissue.DerivedClass",
{
  extend : oopissue.BaseClass,

  construct : function()
  {
    this.base(arguments, new qx.ui.layout.VBox);

    this.myFunc();  
  },

  members :
  {
    myNewFunc() { }
  }

  override : // but now we have two sections for members...
  {
    myFunc: function () 
    {
        console.log("derived");
    }
  }
});
```

It could be also like this:
everything after "@override " until the end of string is actual member name. You have to use string to declare member. It would be theoretically a breaking change, but practically I dunno that someone has ever named his method like "@override <something>".

```
qx.Class.define("oopissue.DerivedClass",
{
  extend : oopissue.BaseClass,

  construct : function()
  {
    this.base(arguments, new qx.ui.layout.VBox);

    this.myFunc();  
  },

  members :
  {
    "@override myFunc": function ()  // would ltrim "@override " and replace myFunc with new declaration
    {
        console.log("derived");
    }
  }
});
```

But in my opinion it does not happen so often, you should just be careful and test your code properly.

**Comment by cboulanger** [comment]
Thanks for your thoughts. It is unlikely that this behavior will be changed since it would break virtually any existing qooxdoo application. Closing.
