### ISSUE TITLE
Allow optional "extend" key

### ISSUE THREAD

**Issue by woprandi** [qooxdoo/qooxdoo#9148]
Qooxdoo does not allow to declare a non-static class without define the superclass. We could consider `qx.core.Object` as the default if no-one if provided.

**Comment by johnspackman** [comment]
I've come across this a couple of times, I think the reason is that there are a few very special classes like `qx.Bootstrap` or `qx.core.Object` itself which inherit from Object (as in the javascript `Object`, not `qx.core.Object`)

I'd happily see this changed though, by having those special classes have `extend: null` or `extend: {}` etc.

If there's no more feedback would you put together a PR?

**Comment by level420** [comment]
@woprandi is this still an issue for you? and more important: if yes: could you please offer a PR for this?
thank you.

**Comment by trupljan** [comment]
I prefer to have base class explicitly declared, it is easier to show such code to someone who does know javascript but does not know qooxdoo.
