### ISSUE TITLE
Error traversing a native Array in IE11

### ISSUE THREAD

**Issue by peuter** [qooxdoo/qooxdoo#9176]
Please see the log output in example: http://tinyurl.com/ztoupfu in Internet Explorer 11. There are two additional indices 'find' and 'findIndex' when traversing through the array `for (var index in array)`.

I would expect the output:
```
0: entry1
1: entry2
```
but I get something like:
```
0: entry1
1: entry2
find: function qx.lang.normalize.Array.find
findIndex : function qx.lang.normalize.Array.findIndex
```

**Comment by peuter** [comment]
Seems to be related to https://github.com/qooxdoo/qooxdoo/commit/63b00838b86672d97fb1de1c4a4aee363a08ae03

@johnspackman Maybe you can have a look?

**Comment by johnspackman** [comment]
you're right, it is because of that commit, but AIUI we are technically required to use `hasOwnProperty` to iterate objects if we want to avoid collisions with prototypes.  EG:

```
  var testArray = ["entry1", "entry2"];
 for (var index in testArray) {
   if (testArray.hasOwnProperty(index))
     this.debug(index+": "+testArray[index]);
 }
```

Although testArray is an Array, it is also an object and `in` is iterating it as an object.

With that said, it's an annoying and breaking change and I'll try using this http://stackoverflow.com/a/22980493/2979698 to hide the shims

**Comment by johnspackman** [comment]
that Object.defineProperty works a treat, I'll post up a PR in a mo.  Other shims could do with the same fix, and AIUI the only backward compatibility issues would <=IE8 which we don't support any more

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9177
