### ISSUE TITLE
Is it possible to use Joose to refactor Qooxdoo?

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qooxdoo#9217]
@konobi recommends using Joose http://joose.it/ to refactor Qooxdoo; this issue is to discuss the practical possibilities and look at how it would work in more detail.  Here's an example class:

```
qx.Class.define("mypackage.MyClass", {
  extend: qx.core.Object,

  construct: function() {
    this.base(arguments);
  },

  properties: {
    alpha: {
      init: null,
      check: [ "one", "two" ],
      transform: "_transformAlpha"
      apply: "_applyAlpha"
    }
  },

  members: {
    _transformAlpha: function(value) {
      return value||"one";
    },

    _applyAlpha: function(value, oldValue) {
      // Some code
    },

    memberMethod: function() {
      return "blah" + this.getAlpha();
    }
  },

  statics: {
    LOOKUP: null,

    staticMethod: function() {
      return 123;
    }
  },

  defer: function(statics, members) {
    statics.LOOKUP = { abc: "one" }
  }
});
```

**Comment by level420** [comment]
I think before starting discussion it would be good if somebody can sum up what the benefits of such a refactoring would be.

**Comment by derrell** [comment]
I'm really interested to see how @johnspackman 's example looks when Joosified. Looking at the Joose documentation, it appears that Joose is more an alternative to qooxdoo, accomplishing some of the same goals, more than something that qooxdoo can build on, but I am eager to be shown how that's not the case.

**Comment by sbusch** [comment]
My observations:

* Last commit more than 3 years ago. That can be Ok for a stable core library which does one thing well.
* No forks on GitHub.
* Web page abandoned: "Joose 3 is currently under very active development. It is already stable with about 800 unit tests, though it may miss some features, presented in Joose 2 (like type system, serialization and some features for attributes)."
* Latest commit to Joose 3 manual on GitHub gh-pages branch more than 5 years ago.

Looks quite stalled to me, nothing to be based on?!

IMHO any class library which ignores ES6 classes shouldn't be considered (although this means a preprocessor is required). qooxdoo should rather strive towards standards and well-known and widely used libraries and tools to reduced maintenance and documentation effort.

**Comment by konobi** [comment]
@sbuch Joose is just feature-complete. There was a pre-existing implementation of a MOP already available to use for reference. This isn't some shiny new framework, it's a single library meant to help with the development of object-oriented projects, so there's little need to keep updating it constantly... there's a limitation to just how much you can do with objects in plain vanillaJS.

@level420 That's a BSD license.

Joose isn't an alternative, it's just a way of allowing you to express the pre-existing object system far more concisely and making the benefits of having a MOP available for use inside and outside the qooxdoo codebase.

I'll get round to showing the class converted, but will have to wait til the weekend or after.

@sbuch the mop doesn't need to care about ES6 classes. If you choose, you can have the MOP implement classes using ES6 classes, but that's an implementation detail that I know I can let the MOP handle. So it's much much more around being able to optimize for code-reuse so you get to concentrate on the application being built rather getting lost in the weeds of worrying about implementation details.

Since the MOP can render the classes for ES6, there's no reason that it can't render classes AS qooxdoo.core ones or some other compositional chunks of code (roles).

**Comment by konobi** [comment]
Oh, and `Joose.Class instanceof Joose.Class` is `true` under Joose. So it's this aspect of selfhosting which is what a lot of folks have a hard time wrapping their head around.

**Comment by konobi** [comment]
So I had a bit of a lightbulb moment in terms of the cognitive gap in terms of where we're coming from. I'm not interested in changing how the qx API works, it should absolutely remain the same.

If you can give me an example of a simple class within the qooxdoo implementation itself, I can translate that using joose. Once a class is an instanceof joose.class, you can do whatever else joose can do within the implementation including all the fun of roles, traits, etc. So you're staging the functionality from beneath, not changing it from above.

that make sense at all?

**Comment by derrell** [comment]
The base class in qooxdoo upon which all others extend is qx.core.Object. Does it make sense to have it extend joose.Class ? If you check out the code, it's in framework/source/class/qx/core/Object.js

**Comment by konobi** [comment]
I'd use it to reimplement Object.js. then qx.core.Object would be a meta-instance of joose. so Just translating that entire file into the joose equivalent. It should actually be a lot shorter overall.

**Comment by derrell** [comment]
Sounds, great @konobi. I'm eager to see qx/core/Object.js translated into the joose equivalent so we can really understand what you're pushing for. So far, this has all been theoretical/hypothetical talk. Where's the beef? :-)

**Comment by konobi** [comment]
I'd like to remind you that it was folks in qooxdoo who asked for external input on code reuse using composition based on others prior experiences with moose/joose/mop/etc. I'm not here to convince you, just assist. I thought reimplementing a small class with the joose equivalent would be useful in assisting in providing better context for the team; but it seems like there's no real interest so I'll just save my time. It would take someone else maybe an hour to work out how to re-implement and existing class with the joose equivalent. Remember, within the qx implementation, not some API breakage. If you do get an interest in looking at the options for doing better code re-use using composition or whatever else, while avoiding the trap of terminology assumptions due to buzzword-ey-ness, drop me a line and I'll be happy to help where I can.

**Comment by hkollmann** [comment]
discussion is outdated. So closed the issue
