### ISSUE TITLE
Method resetSelection of class qx.ui.list.List doesn't work

### ISSUE THREAD

**Issue by goldim** [qooxdoo/qooxdoo#9230]
The class `qx.ui.form.List` in comparison to class `qx.ui.list.List` has properly working method `resetSelection`. Instead of `mylist.resetSelection()` I use the following operation `mylist.setSelection(new qx.data.Array())`.

**Comment by level420** [comment]
@goldim do you mean that ```qx.ui.formList.resetSelection``` does not work?

**Comment by goldim** [comment]
@level420 no, I mean qx.ui.list.List.
Playground example: http://tinyurl.com/zleldu6

**Comment by level420** [comment]
@goldim thank you for clarifying. Do you have some time investigating the cause of this bug? Best would be if you can offer a PR for this ;-)

**Comment by goldim** [comment]
@level420 It's honor for me to take part in improving `qooxdoo` but I am not sure that I can cope with the problem because I don't have any knowledge about internal structure of the framework. But I'll try today, tomorrow or probably in the holidays. If I can not do anything I'll let you know.

**Comment by level420** [comment]
@goldim thank you for helping the community!

**Comment by stahl-riesa** [comment]
Instead of using the resetSelection method use this.getSelection().removeAll() to clear the selection.

The difference is how the selection is stored: qx.ui.form.list uses a private varibale, qx.ui.list.list a property exspecting an qooxdoo array like object. So if you change the selection property of qx.ui.list.list, you change the whole 'selection manager' array.

Maybe it could be helpful to extend qx.ui.virtual.selection.MModel's _applySelection method from
```
value.addListener("change", this._onChangeSelection, this);
if (old != null) {
  old.removeListener("change", this._onChangeSelection, this);
}
this._onChangeSelection();
```
to
```
value.addListener("change", this._onChangeSelection, this);
if (old != null) {
  old.removeAll(); <<< ADDED
  old.removeListener("change", this._onChangeSelection, this);
}
this._onChangeSelection();
```

What do you think?

**Comment by goldim** [comment]
@stahl-riesa Thank you for reply. I tried to find a solution which will resolve this bug. But I can not do anything because of qooxdoo property system. How you said above it is needed to write own methods reset, init, set (etc) and private field to fix this bug. Now about using `this.getSelection().removeAll()` instead of `resetSelection` I've used `setSelection(new qx.data.Array())` this is the same thing and still doesn't resolve the problem with the method `resetSelection`.
I think it's all up to `qooxdoo` developers what they will decide to do with that.

**Comment by johnspackman** [comment]
with the release currently in master, you don't need to implement the property manually - instead, you can use the transform function and change the current property value instead of replacing it.  EG:

```
  properties: {
    
    /** The selection */
    selection: {
      nullable: false,
      check: "qx.data.Array",
      transform: "_transformSelection"
    }    
  },

  members: {
    /**
     * transform for selection property
     */
    _transformSelection: function(value, oldValue) {
      if (oldValue === undefined)
        return value;
      if (!value)
        oldValue.removeAll();
      else
        oldValue.replace(value);
      return oldValue;
    }
```

**Comment by stahl-riesa** [comment]
@johnspackman 
Good proposal! I already thought about that, but don't check if its possible..

**Comment by stahl-riesa** [comment]
The method replace does not exist. Maybe splice is the wanted one, that could help.

BUT:
- selection property needs an qx.data.Array... so you have to use something like splice(x,y,DATAARRAY.toArray())
- even if you change the selection that way, the changeSelection event will not work

Another proposal:
How about adding / implementing modelSelection to qx.ui.list.list?

**Comment by johnspackman** [comment]
method `qx.data.Array.replace` does exist in master, I put it there 😉  https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/data/Array.js#L438-L447

If you don't use master, then `transform` will not have the current value as a second parameter, in which case you can find it by using `this.getSelection()` - but that will throw an exception if it has not been initialised (ie the first time).  

`changeSelection` should fire if the array contents is changed, otherwise IMHO that would be a separate bug because it is legitimate to change the array contents in `qx.ui.form.List`/`SelectBox`/`ComboBox`

adding `modelSelection` is a good idea - you could add that too... 😄

**Comment by stahl-riesa** [comment]
Thank you. Master... I did not notice that. So you are right.

I like the modelSelection feature pretty much because it is very handy.

I c-o-u-l-d add this.

**Comment by level420** [comment]
@goldim @stahl-riesa Would be very nice to have a PR for this! Thank you for trying ;-)

**Comment by goldim** [comment]
@level420 I'll do it later on

**Comment by stahl-riesa** [comment]
If @goldim does not fix it, I will look at that after christmas.

**Comment by level420** [comment]
@stahl-riesa thank you for your offer.
@goldim please report back how we will continue with this issue. thank you.

**Comment by goldim** [comment]
Sorry for my absence. I did not feel very well. Currently I am working on it. I let you know.

**Comment by goldim** [comment]
@level420 I tried to do something with transform method but without any success. I think I can not handle with issue. Sorry.

**Comment by level420** [comment]
@stahl-riesa now back to your offer: could you have a look into this and (if possible) create a PR to solve this? Thank you.

**Comment by stahl-riesa** [comment]
I will look at this.

**Comment by stahl-riesa** [comment]
There are five mixins providing selection features:
- qx.ui.core.MMultiSelectionHandling
- qx.ui.core.MSingleSelectionHandling
- qx.ui.form.MModelSelection
- qx.ui.virtual.selection.MModel
- qx.data.controller.MSelection

qx.data.controller.MSelection and qx.ui.virtual.selection.MModel uses a public property, the other a private variable to save the selected items.

So what is the right way? Unification and standardisation? More than one solution? Changes for transforming the property way to "the normal one"?

**Comment by johnspackman** [comment]
IMHO the best solution would be to use actual properties and use `transform` to implement it; this is because when you implement a property manually (like those mixins) they miss out on the new additions in the future (like Async properties https://github.com/qooxdoo/qooxdoo/pull/9232) and mean that reflection does not work (case in point, binding has to detect properties by looking for "getXxx" and "changeXxx", but sometimes just doesn't bother which causes confusing errors at runtime).

**Comment by level420** [comment]
@stahl-riesa do you think it is possible to fix only this issue, which means only solving the bug reported here? @johnspackman proposed a fix using the transform attribute here https://github.com/qooxdoo/qooxdoo/issues/9230#issuecomment-262454254

**Comment by stahl-riesa** [comment]
How about overriding the resetSelection method like that:

resetSelection : function(resetCurrentSelection)
{
  if( !!resetCurrentSelection )
  {
    this.getSelection().removeAll();
  } else {
    this.base(arguments);
  }
}

**Comment by level420** [comment]
@stahl-riesa could you please create a PR for this? As I've not the use case here it would be best if your or @goldim check your proposal. A PR would be good, as the concrete changes could be evaluated best there. Thank you.

**Comment by stahl-riesa** [comment]
I think, the best solution is to introduce a additional property _useSimpleSelectionHandling_  with a initial value of _false_. If _useSimpleSelectionHandling_  is _true_ then the _selection_ property will only be changed instead of replaced. If you support this, i'll prepare a PR this week.

**Comment by johnspackman** [comment]
I don't agree - the selection property should always be changed, never replaced - this is the convention elsewhere in UI components  - eg anything that includes `qx.ui.core.MMultiSelectionHandling` or `qx.ui.core.MSingleSelectionHandling`, which is pretty much every widget in qx.ui.form.* that supports selection.  

This behaviour is insanely useful, otherwise you have to watch for changes to the selection property value as well as changes to the array - which would mean you have to attach and detach listeners each change etc etc.

IMHO my example in https://github.com/qooxdoo/qooxdoo/issues/9230#issuecomment-262454254 is the correct solution to be used for a PR.  Im happy to submit it when I get a chance :)

**Comment by hkollmann** [comment]
This can not be fixed easily because the synchonisation between the selection manager and the selection property is not working as expected.
You cannot use property binding here because the selection manager qx.ui.virtual.selection.Row do not use properties.

In qx.ui.virtual.selection.MModel i a handwritten synchonization which omits the selection in the selection property when the manager selects a row.

So all calls to resetSelection will do nothing - for the selection there is nothing selected.

I have  now idea how to fix this.

A test project can be found here: https://github.com/qooxdoo/qooxdoo-issues/tree/master/issue_9230

**Comment by johnspackman** [comment]
The issue is that the resetSelection always returns to the init'd value, but does nothing if it the value has not changed from the init'ed value - which it hasn't, because the value is the same array.  Adding a `transform` does not help either, because reset does not support transform, and in any case reset still sees the original value as unchanged.  It's not possible to provide your own implementation of `resetSelection` because the property

The fix is to implement the selection property by hand, because ultimately this is a limitation of the property mechanism.
