### ISSUE TITLE
Menu does not open in latest Chrome (55)

### ISSUE THREAD

**Issue by alp82** [qooxdoo/qooxdoo#9247]
After updating to the latest version of Chrome, the `qx.ui.menu.Menu` click listener does not seem to work anymore. Nothing happens and the menu items are not rendered.

System specs:
- Chrome 55.0.2883.75 m (64-bit)
- Windows 10
- Qooxdoo 5.0.1

Here is example code to reproduce this behavior:

            var menu = new qx.ui.menu.Menu();
            var item= new qx.ui.menu.Button("Menu Item");
            menu .add(item);
            var menuButton= new qx.ui.form.MenuButton("Menu <small>&#9660;</small>", null, menu).set({
                marginLeft: 10,
                alignY: "middle",
                rich: true
            });

The qooxdoo demo browser examples do not work either:
http://www.qooxdoo.org/5.0.1/demobrowser/#widget~Menu.html

**Comment by level420** [comment]
@alp82 this was fixed in master via PR https://github.com/qooxdoo/qooxdoo/pull/9219

Please also note how @vvandens solved this issue with his qooxdoo 5.0.1 application:
https://github.com/qooxdoo/qooxdoo/issues/9182#issuecomment-265161921

Or you could use current master or patch your local copy manually using the code from https://github.com/qooxdoo/qooxdoo/pull/9219

Closing this as fixed
