### ISSUE TITLE
generate pretty removes "finally"

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#9293]
if you have a block of Code like
```
try { 
} catch(e) {
} finally {
}
```
and run generate pretty this block is transformed into

```
 try{
} catch(e) {
}{
}
```
This is wrong JavaScript Code!

**Comment by level420** [comment]
@hkollmann what about `gernerate.py build` does it leave the `try ... catch ... finally``` statement intact?

**Comment by hkollmann** [comment]
generate build leaves the 'try... catch ... finally' intact.

**Comment by hkollmann** [comment]
Steps to reproduce in Framework:

open qooxdoo/Framework Folder
run `generate.py pretty-test'
open source/class/qx/core/Asser.js and have look at line 310. The finally is gone

**Comment by derrell** [comment]
@hkollmann It appears in tool/pylib/ecmascript/frontend/treegenerator_3.py that _finally_ is being handled, but in the backend where it formats it in tool/pylib/ecmascript/backend/formatter_3.py, _finally_ seems not to be handled. I am taking a SWAG (scientific wild-ass guess) that if you add _finally_ to the list on line 129, it just may start to work. Try changing this:
```
for sym in "var new throw while if for do with try catch switch case default".split():  # some of them might get overwritten later, or this list should be adjusted
    prefix_keyword(sym)
```

to this:

```
for sym in "var new throw while if for do with try catch finally switch case default".split():  # some of them might get overwritten later, or this list should be adjusted
    prefix_keyword(sym)
```

I'll be curious to know what effect that has.

Derrell

**Comment by hkollmann** [comment]
You are the greatest!

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9297
closing

**Comment by thron7** [comment]
Here is a bit of background, so maybe the whole story will become clearer.

### 1. Frontend - Transform - Backend
You probably already realized that the source code touching part of the Generator is organized in three parts, frontend, transform and backend. The idea is simply that the frontend parses source code into a syntax tree, transform transforms (or analyzes) the trees, and the backend writes the trees out again as a string (serialization).

The parser itself is sort of two-layered style: The first layer actually breaks up the input string into basic parts (lexing), also categorizing each part into a few rough groups, like number. The second layer then takes this stream of parts and constructs a syntax tree from it.

The important point here is that it turned out that we needed two different trees, one for pretty printing and one for everything else (dependency analysis, compression, etc.). The syntax tree for the pretty printer is 'fat', containing every element from the original source code. The other syntax tree is much leaner, and hence smaller and faster to work with.

### 2. Each tree needs its own backend
Unfortunately, although both the tree generators and the formatters for both trees use all the same mechanics, they needed to be coded separately. Maybe that was a shortcoming on my part, but I couldn't find a good way to share code between the two pipelines.

The import consequence of this is that you have to apply changes, bug fixes, etc. to both pipelines individually. Too sad, but that's the way it is. This is also the reason why Derrell had to add support for a keyword that had been added to the 'compiler' pipeline already.

The "mechanics" common to the treegenerators and formatters is the algorithm called "Pratt Parsing" (or "top-down operator precedence parsing"). The fun thing is that you can use basically the same algorithm for the parser (ie. deserializer) as for the formatter (ie. serializer). The building blocks are the same, whether you have a stream of strings or a stream of tree nodes.

The algorithm as implemented here (taken from an article series by Frederik Lundh) uses lots and lots of classes that take the transformation logic for a specific language construct (e.g. to transform a 'try' tree node to the fully spelled out string "`try { ... } catch (e) { ... `"). The base class for all these classes is pretty simple, see the `class symbol_base` in treegenerator.py. All other classes are built upon this base class.

### 3. "prefix_keyword(sym)"
The main means to construct (or look up) those derived classes is the `def symbol` factory function. So whenever you see the "symbol" function at work, a specialized class to transform some token is created or looked up. Most of the time the call to `symbol()` is done to add or, more often, to override a method of the base class (This changing of classes after they have been defined is sometimes called "open classes"). For example, in the treegenerator.py you'll see `pfix` and `ifix` overridden all over the place, in the formatter modules it is mostly just `format`.

Now, still with the `symbol` helper there a so many different classes you need, and many of them share the same logic. E.g. all standard infix operators can be treated the same (+, -, *, ...), or the increment operators (++, --). So there is another class of helper functions like `infix`, `infix_v`, `prefix`, etc. that handle not just one transformational class, but a whole bunch of them. `prefix_keyword` does this for keywords that start a statement or an expression, like "var", "new", "throw" or "while", that all have their "meat" coming after them, and need - or visually suggest - a blank in between.

I never really liked that all those different kinds of functions are slumped together one after the other, but I never really got around doing something about it. So, there you are. I hope this helps to shed some light on the whole thing.
