### ISSUE TITLE
"[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive." verbose message in Chrome

### ISSUE THREAD

**Issue by firewave** [qooxdoo/qooxdoo#9301]
When changing the console in Chrome to verbose it will display this message. It originates from qx.event.handler.Mouse._initWheelObserver().

I am using qooxdoo 5.0.2 with Chrome 58 beta and 59 canary 64-bit on Windows 10.

**Comment by johnspackman** [comment]
Passive events require that the event is guaranteed to not call `preventDefault()` on the event, but `qx.event.handler.Mouse` will use this event handler to fire the `mousewheel` event - this is a generic event and can be trapped by any application code; because the framework is not able to know in advance whether the application will choose to call `preventDefault()`, we don't know whether using a passive event will be acceptable to the application.

I'm interpreting this message as a suggestion from Chrome, rather than a warning that in future the event will be mandatory passive or something.  The main goal is more responsive UI but it's also so new that people are still figuring out how to best handle it (see [2]) in comparison with other mechanisms.

I'm not against supporting it, just cautious about the best way to handle it.

[1] http://stackoverflow.com/a/37721906

[2] http://stackoverflow.com/questions/41740082/scroll-events-requestanimationframe-vs-requestidlecallback-vs-passive-event-lis

**Comment by level420** [comment]
@firewave Did you try what happens with your application if you set the passive flag to the mouse wheel event listener? Does it work as expected? This would be very interesting. Please report back.

**Comment by level420** [comment]
@johnspackman Interresting SO article [2] on using `requestIdleCallback` instead of `requestAnimationFrame`. It would be wort a try on how qoodoo behaves if we change to `requestIdleCallback`. https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/bom/client/CssAnimation.js#L198-L213

**Comment by johnspackman** [comment]
Yes, I think you might be right 👍   I just read [3] which gives a better rationale as to why to support it.

It's an interesting question as to how often an app would want to prevent the scroll event from being handled; if scroll events are passive by default, we would be able to detect `preventDefault()` on passive events and alert the developer to the environment setting.

[3] https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

**Comment by level420** [comment]
Additional article related to `requestIdleCallback`: https://developers.google.com/web/updates/2015/08/using-requestidlecallback

**Comment by level420** [comment]
@firewave I don't think we currently are able to change the architecture of qooxdoo to use passive event listeners in an automatic way, as qooxdoo attaches listeners to most events and "en-queues" them into qooxdoo's own event handling. As @johnspackman said we are not able to predict from within the framework if an application will call `preventDefault`.

As an option we may enhance the build system (the generator), by adding an option in the configuration file (config.json) which registers all or some event listener with the `{passive: true}` option, which then allows specific applications not calling `preventDefault` to benefit from passive event listeners.
Beforehand we should carefully check if the framework itself needs to call `preventDefault` internally and to not break functionality.

Further reading:
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

**Comment by level420** [comment]
@firewave Could you please explain where you would need passive event listeners and how your qooxdoo application benefits from this? Thank you.

**Comment by firewave** [comment]
I don't need these at all. There verbose messages are generated by the framework when the result of qx.bom.client.Event.getMouseWheel() is passed to qx.bom.Event.addNativeListener() in qx.event.handler.Mouse._initWheelObserver().

I am also seeing the messages "[Violation] 'setTimeout' handler took x ms" and "[Violation] 'requestAnimationFrame' handler took x ms" (from application and framework code) which are obviously more informative about the responsiveness about the JavaScript code - hence they are being "verbose" message.

But I do seem to remember something about that browser won't to intervene with certain patterns in code, that might cause sloppiness. Could just be the behavior that setTimeout() is throttled in inactive tabs, but that seems something very recent and it's was definitely a while back when I think I read something like that.

Since the "wheel" only came from the framework and was very specified I though I pass it on since having more responsiveness in the framework doesn't seem like a bad thing.

I also thought it could have been something that was overlooked like #9298. After all it's been quite a while since the last qooxdoo feature release.

So if there is nothing to be changed or what could be changed I would be totally fine with it.

**Comment by johnspackman** [comment]
I've created a branch at [1] which adds debug-only tests - it will issue warnings if the event is `preventDefault()`-ed or if the time taken for the event is over 100ms (and an error message if it is over 500ms).  In theory, if enough people use this without getting warnings about `preventDefault()` we would have some comfort that adding passive events would be acceptable (at least in the general case)

[1] https://github.com/johnspackman/qooxdoo/tree/passive-scrolling

**Comment by lucapivato** [comment]
I have added to our build an optional passive argument to qx.bom.Event.addNativeListener() and set it to false in qx.event.handler.Gesture._initObserver otherwise we get hundreds of errors when wheel scrolling textArea, table, etc. I can put in a pull request if you think this is the right fix for qooxdoo. It has also a "event.passive" check in qx.bom.client.Event and qx.core.Environment.

**Comment by johnspackman** [comment]
@lucapivato sounds reasonable, please go ahead with a PR 👍
