### ISSUE TITLE
Bad table widget performance -> solution included

### ISSUE THREAD

**Issue by rstmm** [qooxdoo/qooxdoo#9302]
Hi,

I can't spend the time to prepare a pull request, but I wanted to share a solution to improve the table widget performance of qx desktop. The solution has been tested on 5.0.1 and avoids modifying framework files as good as possible.

The problem is, that tables with many columns are locking up browser a long time when the model is initially set. E.g. with 78 columns (yes real world example showing table with technical data) it locks the browser 30s to 5 minutes, depending on used browser and hardware.

The reason:
Qooxdoo creates and disposes each header cell 78*2 times when the model gets set initially, resulting in creation and disposal of 12.168 header cell widgets (which may include more widgets). In our case this resultet in unnecessary creation and disposing of > 100.000 widgets (since we have a small filter widget in the header cells) only when loading the table. The more columns, the worse the problem.

Detailed steps:

> 1. Table data loaded, we set the table model on the Table object
> 2. qx Table calls _applyTableModel. First statement in it calls init function on qx.ui.table.columnmodel.Basic
> 3. qx.ui.table.columnmodel.Basic.init() loops through all 78 columns, sets some values and within each of the 78 loops it fires a visibilityChangedPre event. (=78 visibilityChangedPre events)
> 4. qx.ui.table.pane.Model listens on this event and fires a "modelChanged" event for each received event (=78 modelChanged events)
> 5. qx.ui.table.pane.Scroller listens to modelChanged events and calls "onPaneModelChanged" function on its qx.ui.table.pane.Header (=78 function calls)
> 6. onPaneModelChanged calls "_updateContent" on itself with a "completeUpdate" parameter set to true (=78 function calls)
> 7. _updateContent with this parameter set to true forces the function to call "_cleanUpCells" on itself (=78 function calls)
> 8. _cleanUpCells disposes each header cell (=78 objects)
> 9. _updateContent now re-creates all 78 header cells and renders the whole header again
> 
> Additionally, when setting the 78 header cell renderers, qx.ui.table.pane.Model again fires the model changed event 78 times with the same effect.

Solution (I did not want to modify qx files to be update save as good as possible): Debounce the model change event by 50s. This makes sure it is called once instead of 156 times.

1. One change needed in qx.ui.table.pane.Model -> Add following function:
```
_resetColumnCount: function() {
    this.__columnCount = null;
}
```

2. Add optimized model:

```
qx.Class.define("xx.tableview.view.OptimizedTablePaneModel", {
    extend: qx.ui.table.pane.Model,

    construct : function(tableColumnModel)
    {
        this._fireModelChangedDebounced = qx.util.Function.debounce(this.fireEvent.bind(this, qx.ui.table.pane.Model.EVENT_TYPE_MODEL_CHANGED), 50);

        this.base(arguments, tableColumnModel);
    },

    members: {

        _fireModelChangedDebounced: null,


        /**
         * Event handler. Called when the visibility of a column has changed.
         *
         * @param evt {Map} the event.
         */
        _onColVisibilityChanged : function(evt)
        {
            // this function is not available in framework but we need it because we cannot access the private member
            // After updating qooxdoo it will be missing and has to be added to qx.ui.table.pane.Model like this:
            //_resetColumnCount: function() {
            //      this.__columnCount = null;
            //},
            this._resetColumnCount();

            this._fireModelChangedDebounced();
        },


        /**
         * Event handler. Called when the cell renderer of a column has changed.
         *
         * @param evt {Map} the event.
         */
        _onHeaderCellRendererChanged : function(evt)
        {
            this._fireModelChangedDebounced();
        }
    }
});
```

Use optimized model:
```
 control = new qx.ui.table.Table(null, {
     // FIX bad performance due to bad qx implementation
    tablePaneModel: function (obj) {
       return new xx.tableview.view.OptimizedTablePaneModel(obj);
   }
});
```

Maybe somebody has the time to integrate my solution into the framework or wants to use the same solution.

**Comment by level420** [comment]
@rstmm thank you for opening this issue.

The table widget has a big performance issue if when adding column header renderers. I wrote a stackoverflow answer (http://stackoverflow.com/questions/40679293/qooxdoo-table-tooltips-performance/40767775#40767775) about that which targets the same problem, but your solution seems to be better! Here is my solution.

As you investigated a lot into this issue, it would be great if you could offer a PR for this.

Creating the PR is simpler than think:

1. fork qooxdoo by clicking the "Fork" button on this page
2. go to the forked repo (https://github.com/rstmm/qooxdoo ) and navigate in the master branch to file you want to change
3. find the "edit" button (the pencil icon) and make your changes
4. save the changes (at the bottom of the page, button "propose file change") by creating a new branch giving it a meaningful name (e.g. containing the issue number) and some meaningful commit change information
5. edit other files and add them to the same branch
6. go to the main page of your fork ( https://github.com/rstmm/qooxdoo )
7. find the button "Compare & pull request" and click.  
8. the base  (default qooxdoo/qooxdoo:master) and the head fork (default your branch created in step 4) should be pre selected. add some meaningful information in the the fields below
9. click "Create pull request"

You're done. You can create all tasks via githubs browser interface. No need to install something locally.

Give it a try!

**Comment by mever** [comment]
Hi,

The main reason why performance is bad is because the table listens to changes on the table-column-model (TCM). This is fine when changing the width (or other property) of a single column, but not when constructing the table for the first time. I have fixed it by configuring the TCM first and then construct the table. Not the other way around (this still needs some hacks though). I share how I do this in a pull request for this issue.

In a somewhat related note: I also added a lot of other functionality. My own table class uses the one from Qooxdoo but adds these features:
 - Swappable data model implementation.
 - Remote model row data conversion.
 - Extensible by sub-classing and mixins.

I have build a table class {table.Table} that supports swapping the data model and columns. This is done by using {qx.ui.table.Table} as member. I also build a lot of components. Each optional and usable by extending the {table.Table} class. For example:
- By extending {table.Table} and importing the 'row level data binding' mixin you can data bind the selected row.
- More cell and editor renderer factories.
- OO access to fields, filters and sorting.

All functions are well designed, tested and don't leak memory. I am planning to release the table package the coming month in order to contribute back to the community. I still need to find out how much I am going to release, because many classes are designed to support our domain and is of little use to the community.

**Comment by oetiker** [comment]
@mever is your extended table object backward compatible? in that case it would be great if you made it a PR for qooxdoo proper instead of releasing it separately.

**Comment by mever** [comment]
@oetiker I had to subclass the basic column model and overwrite the init method. As you can see, it doesn't call the base method if a table is given (this is what other classes except my own do). My code calls the init method with the column count and without second argument to initialize the TCM.

The rest is backwards compatible.

This is the entire subclass:
```
qx.Class.define("my.table.columnmodel.Default",
{
  extend : qx.ui.table.columnmodel.Basic,
  implement : [ my.table.IColumnModel ],
  members :
  {
    /**
     * Initializes the column model.
     *
     * This is a ugly hack to prevent the TCM from resetting when the table is using it.
     */
    init : function(colCount, table) {
      if (! table) {
        this.base(arguments, colCount);
      }
    }
  }
});
```

**Comment by mever** [comment]
I did some further research and made this playground example to demonstrate the problem: [link to playground](http://www.qooxdoo.org/devel/playground/#%7B%22code%22%3A%22var%2520button1%2520%253D%2520new%2520qx.ui.form.Button(%2522First%2520Button%2522%252C%2520%2522icon%252F22%252Fapps%252Finternet-web-browser.png%2522)%253B%250Avar%2520check%2520%253D%2520new%2520qx.ui.form.CheckBox(%2522Slow%2522)%253B%250Avar%2520doc%2520%253D%2520this.getRoot()%253B%250Adoc.add(button1%252C%2520%257B%2520left%2520%253A%2520100%252C%2520top%2520%2520%253A%252050%2520%257D)%253B%250Adoc.add(check%252C%2520%257B%2520left%2520%253A%2520300%252C%2520top%2520%2520%253A%252050%2520%257D)%253B%250Abutton1.addListener(%2522execute%2522%252C%2520function(e)%2520%257B%250A%2520%2520%2520%2520try%2520%257B%250A%2520%2520%2520%2520%2520%2520var%2520t%2520%253D%2520(new%2520Date()).getTime()%253B%250A%2520%2520%2520%2520%2520%2520buidlTable(!!check.getValue())%253B%250A%2520%2520%2520%2520%2520%2520this.info((new%2520Date()).getTime()%2520-%2520t)%253B%250A%2520%2520%2520%2520%2520%2520%250A%2520%2520%2520%2520%257D%2520catch%2520(e)%2520%257B%250A%2520%2520%2520%2520%2520%2520console.log(e)%253B%250A%2520%2520%2520%2520%257D%250A%2520%250A%257D)%253B%250A%250Avar%2520buidlTable%2520%253D%2520function(slow)%2520%257B%250A%2520%2520%250A%2520%2520%2520%252F%252F%2520make%2520model%250A%2520%2520var%2520m%2520%253D%2520new%2520qx.ui.table.model.Simple()%253B%250A%2520%2520var%2520columns%2520%253D%2520'abcdefghijklnmopqrstuvwxyz'.split(%2522%2522)%253B%250A%2520%2520m.setColumns(columns)%253B%250A%250A%2520%2520%252F%252F%2520now%2520table%250A%2520%2520var%2520t%2520%253D%2520new%2520qx.ui.table.Table(m)%253B%250A%2520%2520var%2520tcm%2520%253D%2520t.getTableColumnModel()%253B%250A%2520%2520%250A%2520%2520%252F%252F%2520then%2520configure%2520columns%250A%2520%2520columns.forEach(function(_%252C%2520col)%2520%257B%250A%2520%2520%2520%2520if%2520(slow)%2520%257B%250A%2520%2520%2520%2520%2520%2520tcm.setColumnVisible(col%252C%2520Boolean(Math.round(Math.random())))%253B%250A%2520%2520%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520%2520%2520tcm.setColumnWidth(col%252C%2520Math.round(20%2520%252B%2520Math.random()%2520*%252080))%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%257D)%253B%250A%250A%2520%2520doc.add(t%252C%2520%257B%2520left%2520%253A%2520100%252C%2520top%2520%2520%253A%2520100%2520%252B%2520doc.getChildren().length%2520*%252050%2520%257D)%253B%250A%257D%253B%22%2C%20%22mode%22%3A%22ria%22%7D)

As you can see there, the table is optimized for some column changes and not others. In my own (currently private) implementation I set the visibility of columns before adding the model (with some hacks). One way to solve the bad performance is to optimize operations on the table. This, however, can be a pain. Usually it is better to make a initial configuration first then listen for changes.

I also have the tendency to refactor bits and pieces of the table. I.e. better segregate the TCM in order to configure it, before adding it to the table.

**Comment by Plasmodino** [comment]
Not only the header is affected. Whenever the width of a column is set, the content of the table is redrawn twice. If data is already loaded and you initially set the width of 129 columns at once like in my case, the pane content is redrawn more than 260 times. There seems to be no way to set all the widths in one call and redraw the panes afterwards once.

**Comment by adrelino** [comment]
I just stumbled upon this open issue now, 5 years later, and was wondering if the performance issues are fixed by now? Because we also have tables with a lot of columns and I always thought having lots of rows was the problem...

**Comment by johnspackman** [comment]
not as far as I know - but it would be great to have a PR before it gets lost in the midst of time :)
