### ISSUE TITLE
Table: When creating meta columns, all the widths of the scrollers but the last one are calculated wrong

### ISSUE THREAD

**Issue by Plasmodino** [qooxdoo/qooxdoo#9309]
In Scroller.js the PaneWidth is calculated so:

			setPaneWidth: function (width) {
				if (this.isVerticalScrollBarVisible()) {
					width += this.getPaneInsetRight();
				}
				this.setWidth(width);
			},
This happens for all the scroller widths in Table.js:

    _updateScrollerWidths : function()
    {
      // Give all scrollers except for the last one the wanted width
      // (The last one has a flex with)
      var scrollerArr = this._getPaneScrollerArr();

      for (var i=0; i<scrollerArr.length; i++)
      {
        var isLast = (i == (scrollerArr.length - 1));
        var width = scrollerArr[i].getTablePaneModel().getTotalWidth();
        scrollerArr[i].setPaneWidth(width);

        var flex = isLast ? 1 : 0;
        scrollerArr[i].setLayoutProperties({flex: flex});
      }
    },

Solution in Table.js, applyMetaColumnCounts():
Call
this._updateScrollBarVisibility();
**before**
this._updateScrollerWidths();

Otherwise there is a gap between the meta columns if there is a vertical scrollbar visible in table and you split the table into two meta columns.

**Comment by schnepe2** [comment]
Hi @Plasmodino,
I've tried to understand what the problem is, but I can't figure it out.
I've created a playground example that uses (a) the original table and (b) your proposed fix.
But I can't see any difference :man_shrugging: 

http://tinyurl.com/kphwgej

The changed playground `FixedTable` Class looks weird, but as we can't access private members in an overridden `_applyMetaColumnCounts` method, I've just added a flag to skip the `_updateScrollerWidths` method when it's called from `_applyMetaColumnCounts`...
All this should resemble your fix 
> in Table.js, applyMetaColumnCounts():
> Call
> this._updateScrollBarVisibility();
> before
> this._updateScrollerWidths();

So, could you maybe change that playground example, so I (we) can see the problem?
...adding meta columns or whatever triggers the issue...

**Comment by level420** [comment]
@schnepe2 thank you for looking into this. :+1:

**Comment by adrelino** [comment]
I also just noticed a similiar issue in that there is only a useful horizontal scroolbar in the last scrollbar.
The scrollbar of the first meta column (responsible for the first two columns) just fills the complete width (of the two first columns) so there is nothing to scroll.

![image](https://user-images.githubusercontent.com/6432001/96467247-03b4b400-122b-11eb-986a-ee184ac00933.png)

I modified the example from the playground with the 4 columns and just called:
`table.setMetaColumnCounts([2,-1]);` or `table.setMetaColumnCounts([2,2]);`
see https://tinyurl.com/y4azovb6.

Am I missing something? e.g. is there a way to set the width of the metacolumn to a smaller value so that the scrollbar width is adapted accordingly? Or is this impossible currently?

**Comment by adrelino** [comment]
I just patched https://github.com/adrelino/qooxdoo/commit/70ac4be1a80d78981dd499263340ee9132ba5e65 Table.js and Scroller.js a bit to be able to set the MetaColumnWidth via right-click dragging starting in the rightmost column of the meta column. Is that worth integrating into qooxdoo?

**Comment by oetiker** [comment]
sounds sensible ... is there a demo ?
