### ISSUE TITLE
Chrome 56 json.js throwing error with developer tools opened

### ISSUE THREAD

**Issue by rstmm** [qooxdoo/qooxdoo#9326]
Hi,
seems like Chrome 56 is having a problem with Dev tools opened. When we try to parse any json, it complains:
"SyntaxError: Unexpected token in JSON at position 1"

In Chrome 55 this does not happen.

It is complaining on the `parse(` call in:

```
try {
  // Safari <= 5.1.2 and FF 3.1b1 allow unescaped tabs in strings.
  parseSupported = !parse('"\t"');
} catch (exception) {}
if (parseSupported) {
  try {
	// FF 4.0 and 4.0.1 allow leading `+` signs, and leading and
	// trailing decimal points. FF 4.0, 4.0.1, and IE 9-10 also
	// allow certain octal literals.
	parseSupported = parse("01") !== 1;
  } catch (exception) {}
}                 
```

Enter `parse('"\t"')` in the console and the same error is shown.

![grafik](https://cloud.githubusercontent.com/assets/12029804/25894347/b56f95e2-357b-11e7-9c3b-aeebd268c801.png)

**Comment by johnspackman** [comment]
This is expected behaviour; the code is testing the browser's behaviour to see whether the browser's implementation of `JSON.parse()` works properly.  Unfortunately, in this specific case this will throw an exception in browser if the browser has a proper implementation, which means that every time you start the app when you have "Pause on caught exceptions" turned on you hit a break point, as well as getting a warning in the console.

It is annoying, and it would be great if the results of this kind of detection were cached in (for example) local storage so avoid the constant breakpoints (I have 6 every time I refresh my apps for example) but that's just an idea right now ...

**Comment by rstmm** [comment]
ok you are right, I didn't see my collegue has this option activated.
