### ISSUE TITLE
Webpack based qooxdoo/cli

### ISSUE THREAD

**Issue by adrelino** [qooxdoo/qooxdoo#9328]
## Qooxdoo CLI similar to Angular CLI
As mentioned on gitter, I lately developed an Angular 4 app. To get started quickly I used the npm package and github project [Angular CLI](https://github.com/angular/angular-cli).
`npm install -g @angular/cli`
It installs the command line interface tool `ng` globally, which allows to easily boostrap a new project with boilerplate code and to run a development server with live-reload functionality:
```
ng new PROJECT-NAME
cd PROJECT-NAME
ng serve
```

Since this is really neat, I want to be able to do the same with qooxdoo apps in the future.
`npm install -g qooxdoo/cli`
```
qx new PROJECT-NAME
cd PROJECT-NAME
qx serve
```
this is nearly the same suggestion as in #9325.

## Webpack, qooxdoo generator, and qxcompiler
Under the hood, the angular cli tool `ng` is based on [webpack](https://webpack.js.org/), which takes care of transpiling/compiling TypeScript to ES5, bundling the modules and running the development server which watches for changes in the source files to start off a new compilation run and reload the browser (at least I think so, I'm definately no webpack expert). As I have heard, nowadays one **doesn't even need build tools like grunt/gulp** anymore for these tasks, since the tasks they were used for are now handled by a module bundler such as webpack as well.

Conceptionally, I understand that the qooxdoo generator is very similar to webpack, just that it is written in python and webpack is written in Node.js. I recently stumbled on Sebastian Werner's (@swernerx, one of the original qooxdoo authors) presentation on Webpack Tuning, where he states
> Webpack == qooxdoo generator or jasy
see: https://speakerdeck.com/swernerx/webpack-tuning?slide=5

I also know of @johnspackman's great effort to bring qooxdoo generator to javascript with his [qxcompiler](https://github.com/johnspackman/qxcompiler). 
However, I think that a lot of functionality that was in the qooxdoo generator is already available in webpack, especially regarding bundling of source files but also of css and image files.

So my question to @swernerx is what features a webpack-based qooxdoo/cli actually needs and to @johnspackman if these features are already available in qxcompiler? 

## Overview over the JavaScript Ecosystem Development Tools in 2017
Since there are a lot of tools used for the development of webapps nowadays, I will try to give an overview since I think it can be helpful for the further discussion about what the qooxdoo cli actually is. In general, the tools the JavaScript Ecosystem offers for web development can be put into 5 categories:
1. Package Managers
 * npm
 * bower
2. Module Systems
 * AMD/RequireJS
 * CommonJS
 * ES6 (ECMAScript 6) native modules
3. Transpilers
 * Babel (ES6->ES5)
 * TypeScript (type-enhanced JS Syntax -> ES5)
 * CoffeScript (python-like syntax -> JS/ES5)
4. Build tools/task runners
 * Grunt
 * Gulp
5. Module bundlers
 * SystemJS
 * Browserify
 * Webpack  
 
(1.) is used to manage and install third-party dependencies, 
(2.) to modularize code with imports, 
(3.) if one prefers to write in another language that compiles to JavaScript, 
(4.) to automate certain build or deployment tasks, 
(5.) to reduce the number of files needed to deliver to a client to improve performance.

from [The JavaScript Ecosystem Demystified](https://differential.com/insights/the-javascript-ecosystem-demystified/) More details in: [Overview of the JavaScript ecosystem](https://medium.com/@bojzi/overview-of-the-javascript-ecosystem-8ec4a0b7a7be)
and [A JAVASCRIPT ECOSYSTEM OVERVIEW](http://www.imaginarycloud.com/blog/a-javascript-ecosystem-overview/)

## Qooxdoo development in the future
So how does qooxdoo fit in above categories? 

1. There are multiple qooxdoo packages on npm, both official ones, unofficial ones, some that contain just the server part of qooxdoo, some that contain the sdk, and some that contain the compiler or other tools. But there is ongoing work in #9137 to clean up the mess and reduce the confusion.
2. The module system is somehow implicit, i.e. there are no imports on top of a file where one defines a new qooxdoo class, i.e. [qx.ui.basic.Label](https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/basic/Label.js)
`qx.Class.define("qx.ui.basic.Label",{extend : qx.ui.core.Widget, ... })` so the code for core.Widget gets imported automatically by qooxdoo generator after analyzing all the source files? Would it make sense to switch to ES6 native modules instead?
3. The language qooxdoo is written in valid ES5 javascript, but actually it is has quite a specific syntax using `qx.Class.define` to mimic class-based OO when classes where not yet native to JavaScript like they are now in ES6. So do we need to extract the qooxdoo-lang transpiler from the generator and reimplement it using Node.js? Or does it make sense (in the long term of course) to switch from `qx.Class.define` to native ES6 classes or, even better, move the whole SDK gradually to TypeScript?
4. Qooxdoo comes with a Gruntfile (https://github.com/qooxdoo/qooxdoo/blob/master/framework/Gruntfile.jss), but it only allows to call qooxdoo generator jobs via grunt. So I think we don't need a task runner / build tool in the future.
5. So far, the bundling of javascript source files into one large track,js and that of assets was done by qooxdoo generator as well. I think webpack will allow to do most of that for us much faster and better than before, we just have to find out how to configure it properly.

**Comment by marcelr** [comment]
Excellent summary!
If we start a new qooxdoo npm/ES6 approach the most important is that we have the patience to go persistently until the final last bit and bits. At any time, it should be productively usable.
Otherwise we end up with another half finished piece.
Or in other words: This has to be THE qooxdoo path everybody trusts in.

**Comment by oetiker** [comment]
@marcelr as I said already in the chat, I don't think that this is a matter that will be decided 'in theory'. We already have an excellent build system, and incentive to switch to something new will come from the benefits there are to gain from such a switch ... especially if they make qooxdoo work even better in the ways a qooxdoo application works ... 

in other words, if you have ideas how to improve the build infrastructure using existing components from the node eco system, create a little proof of concept of what you imagine ...

**Comment by johnspackman** [comment]
@adrelino we're very nearly there in terms of what I think you're asking for, it's just taking time to finish it all off.

The key thing is that qooxdoo does not need units to be explicitly imported with `require` or similar - the JS class is read, dependencies are calculated, and a load order.  When it comes to compiling an application then, this function takes care of (1, (2), and (5) - personally, coming from a Java and C++ background I find this kind of thing a welcome relief over `require`, and is probably only possibly because of the strict OO structure of classes that Qooxdoo has.

This already works with the generator, which is a python app and to be replaced with  [qxcompiler](https://github.com/johnspackman/qxcompiler) - and qxcompiler adds Babel transpiler and is fast enough to do almost real time constant compilation/transpilation.  It's built as an API first, so other transpilers could conceivably be added in too - and because it's an API, implementing grunt/gulp/brocolli/etc plug-ins is pretty straightforward too.

**Comment by cboulanger** [comment]
As I understand, one of the core ideas of the rewrite is to reduce the functionality of the old python generator to the absolutely necessary parts which cannot be substituted by other node modules. Then we can compose everything else from there. That is, to ship a minimal CLI to do the most basic functionality with the framework, and have independently maintained and versioned boilerplate code for whatever tool chain somebody likes best, to be installed with npm.

**Comment by johnspackman** [comment]
The intention is to go further than that and remove the dependency on python altogether; the python generator part 'make', part batch system, part compiler; having the compiler functionality replaced in JS in qxcompiler means that the other functions are (I think) all easily replaced with other modules (eg grunt) or easily written new modules

**Comment by cboulanger** [comment]
Sorry, I was unclear. What I meant was that the NodeJS-based generator is not a 1:1 replica of the more monolithic python one, but, as you say, a composable unit...

**Comment by kreimer** [comment]
Hi there, I don't know if anyone else but me is using the qx part system. @johnspackman Do you mean that future releases of qooxdoo won't support parts?

**Comment by adrelino** [comment]
Thanks for your input.

## Possible roadmap to qooxdoo >= 6.0.0
@marcelr, @cboulanger 
I think the transition has to be a 2-step process
_First_, allow users of qooxdoo to use the library just as any other ES6 or even TypeScript library (#9324), withouth the need to call .generate.py anymore. That way, new users don't even have to learn the domain specific qooxdoo language (lets call it qooxdoo-lang) with its non-standard class, property and interface definitions and inheritance concept, since the way to do this is now standardized in ES6 (class) or TypeScript (interfaces). This means that future qooxdoo development could look like this: 
```
class MyPage extends qx.ui.tabview.Page {
    constructor(name) {
        super(name);
        this.setLayout(new qx.ui.layout.Flow());
        this.setShowCloseButton(true);
    }
}
```
from: https://github.com/jbaron/qx-typed/blob/master/application.ts#L145
Furthermore, the module system is also standardized now, which means that users have to import the specific parts of the qooxdoo application that they want to use instead of relying on the 'magic' of generate.py to correctly find all classes that are used automatically.


_Secondly_, slowly migrate exisiting library code step-by-step to ES6 or TypeScript to finally (in ~2022) get rid of the qooxdoo-lang -> ES6 transpile step and the typings file.





## Modules
@oetiker 
The qooxdoo build system **was** excellent when it was invented 10 years ago, it provided code modularization withouth the need for require/import..., a transpiler for the domain specific qooxdoo-lang allowing for easy OO programming with classes and inheritance, bundling of js but also of assets like png's and css etc...  However, having all these features packed into just one tool takes the freedom from our users to choose their preferred build/bundle system. The benefits from a switch are multifold: shorter build time, potentially faster execution time (through better compilers in combination with type annnotations, dead code elimination, tree shaking), no more need for a Manifest file...   

I think a crucial first step to bring qooxdoo forward is to allow it to be used easily with mainstream bundlers (webpack but also rollup or even browserify) and minifiers (e.g. uglfiy). The way to go here is to provide the source as native ES6==ES2015 modules. E.g. this was lately done in the 4.0.0 release of the openlayers library:

> For users of mainstream bundlers and minifiers, OpenLayers is now also available as a set of ES2015 modules. See https://npmjs.com/package/ol/. With that package, bundling only the needed parts of the library with an application is now completely hassle free.

from: https://github.com/openlayers/openlayers/releases/tag/v4.0.0
See also the ol npm package: https://www.npmjs.com/package/ol/
and the discussion: https://github.com/openlayers/openlayers/pull/6302

If this sounds good in theory and if we want the same in qooxdoo, I will go forward to start a little proof of concept following the path openlayers took. However, I will definately need a little help to

## Transform qooxdoo-lang sources to ES6/Typescript
@johnspackman This doesn't mean that we have to rewrite the whole library immediately in ES6 by inserting import/export statements to the top of each class file by ourselves, rather, a combination of [qxcompiler](https://github.com/qooxdoo/qxcompiler), which computes the dependency graph, together with [qxparser](https://github.com/jbaron/qx-parser) adapted to ES6 instead of TypeScript could do that job for us. 

For example, openlayers is still developed using closure compiler, but the authors added a build target which exports the source as ES6 modules using [jscodeshift](https://github.com/facebook/jscodeshift) , which basically replaces goog.require with import:

> The branch includes a codemod (for use with jscodeshift) that transforms our sources into ES6 modules. Running make package generates modules in the build/package directory. The ol package can then be published from this directory. 

from: https://github.com/openlayers/openlayers/pull/6302

## Parts
@kreimer 
Lazy loading of infrequendly used parts of a large application is an important feature to reduce initial load size and improve the user experience. However, I think the parts system (http://www.qooxdoo.org/5.0.1/pages/development/parts_using.html) that is implemented in the current python generator can be dropped since this functionality can be reproduced better with exising javascript tools in combination with ES6 modules. It can be accomplished with the async code splitting features of today's bundlers, e.g. https://webpack.js.org/guides/code-splitting-async/:
The syntax would have to be changed from:
```
qx.io.PartLoader.require(["custom"], function(){
  var part = new custom.Settings()
});
```
to
```
import('custom').then(function(custom) {
  var part = new custom.Settings()
})
```

**Comment by cboulanger** [comment]
Hi @adrelino, thank you for your suggestions. I wonder, though, if you have a sense of the magnitude of the changes that would be required to implement what you have in mind. The qooxdoo toolchain as it is right now might not be the most modern way to do things, but it is the product of thousands of person-hours, tried and tested, and works very well. There is no way this can be replaced in one piece. Instead, we'll have to take an evolutionary strategy that supplants the existing system and adds ES6 support to the existing class system. Then, as a next step, one could look at supporting ES6 classes. They look nicer, to be sure, but there is little functional advantage compared to the existing system. They don't have mixins, so we would have to think about how to  do that (It might be doable once function decorators have landed, which won't be long). And so on. I think we'll have to adopt a piecemeal approach to suport modern JavaScript, and see where it leads us, having the "traditional" machinery as a fallback.

**Comment by adrelino** [comment]
> Hi @adrelino, thank you for your suggestions. I wonder, though, if you have a sense of the magnitude of the changes that would be required to implement what you have in mind. The qooxdoo toolchain as it is right now might not be the most modern way to do things, but it is the product of thousands of person-hours, tried and tested, and works very well. 

Hi @cboulanger. These are valid concerns. However, I am afraid that qooxdoo looses momentum and that all these person-hours (that first 1&1 and then the small qooxdoo open-source community invested) will be wasted. Tho qooxdoo toolchain works very well but does not integrate well with other tools for large-scale application development which also uses dozens of other tools and libraries. `npm install -g qooxdoo/cli` and `qx new PROJECT-NAME` just has be supported to lower the entry barrier for new users coming e.g. from an angular world to qooxdoo. 

> There is no way this can be replaced in one piece. Instead, we'll have to take an evolutionary strategy that supplants the existing system

The magnitude of these changes definitely requires an evolutionary strategy. That is why I put 2022 as a long-term goal to migrate the whole library from qooxdoo-lang to >=ES6. Until then, we should just provide users a way to use the library as ES6 modules even if it is still written in qooxdoo-lang and compiled into ES5 with generate.py

> and adds ES6 support to the qooxdoo class system. 

With that, do you mean the work of @johnspackman who added a babel transpile step to qxcompiler, so that one can use core ES6 language features (let, arrow functions etc., but excluding classes and inheritance, for which we still use the original qooxdoo OO class system), something that is not possible with generate.py?


 

> Then, as a next step, one could look at supporting ES6 classes. They look nicer, to be sure, but there is little functional advantage compared to what we have right now. They don't have mixins, so we would have to think about how to do that (It might be doable once function decorators have landed, which won't be long). 

There is actually Mixin support in ES6 via Mixin factory functions.  The syntax works in combination with the usual extends keyword
```
var squareMixin = Base => class extends Base {
  square(a) {return a*a}
};
class Foo { }
class Bar extends squareMixin(Foo) { }
```
from: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Mix-ins

The factory function Mixin support also made it into [TypeScript >= 2.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html). However, ES6 does not have interfaces (and no implements keyword), but TypeScript does:

```
interface ClockInterface {
    currentTime: Date;
    setTime(d: Date);
}

class Clock implements ClockInterface {
    currentTime: Date;
    setTime(d: Date) {
        this.currentTime = d;
    }
    constructor(h: number, m: number) { }
}
```
from: http://www.typescriptlang.org/docs/handbook/interfaces.html
If I think about it, an Interface gives a guarantee about the type of an object. Since ES6 is not typed, it can only check if an object/class instance implements an interface at runtime.  However, in typescript, one can check statically If a class really implements an interface. So to reproduce the functionality of qooxdoo-lang + generate.py which can check if an interface is fully implemented, ES6 might not be sufficient, we would need TypeScript.

> And so on. I think we'll have to adopt a piecemeal approach to suport modern JavaScript, and see where it leads us, having the "traditional" machinery as a fallback.

Yes. I suppose the following piecemeal approach:

1. As a starting point, let's try to add TypeScript support #9324 by integrating the functionality of the typing file generator which parses qooxdoo's api (implemented in [main.ts](https://github.com/jbaron/qx-parser/blob/master/src/main.ts)) into qooxdoo's main repository. 
2. This will give us a (qooxdoo-lang -> ES5) compiled qooxdoo.js (using generate.py/qxcompiler) as well as a [qooxdoo.d.ts](https://github.com/jbaron/qx-parser/blob/master/qooxdoo.d.ts) typings file (using main.ts above), which we should publish on npm and update with each new qooxdoo release. The typings file uses TypeScript's `declare module` (https://www.typescriptlang.org/docs/handbook/modules.html) syntax to make qooxdoo's functionality available as modules
3. Then, we can allow users to do `npm install qooxdoo` and develop code like in https://github.com/jbaron/qx-typed withouth having to run generate.py.


Following that, we can do the following improvements under the hood, withouth changing the new modern API
* Transform the library source into ES6 modules (instead of just using declare module in an additional typings file) to get features such as Tree Shaking, Parts, etc... let's do this similar to how openlayers did it. @johnspackman Is it possible to for qxcompiler to transpile each qooxdoo source file from qooxdoo-lang to ES5 individually, withouth bundling referenced classes, and outputting the dependency graph of it? Then a simple codemod could just add import/export definitions from the dependency graph to the top of these ES5 files to make them ES6.
* In the very long run, replace qooxdoo-lang's object orientation with >=ES6 classes, mixins and TypeScript interfaces. Then, we could finally drop generate.py or even qxcompiler. Possibly, we might not even need a Babel or even TypeScript transpiler from the JavaScript ecosystem anymore, since standardized ECMAScript or even TypeScript features will eventually be implemented in future browsers directly.

**Comment by johnspackman** [comment]
Hi @adrelino, there's a lot of points above I'll try and cover them all :)

I think there are some problems with migrating Qooxdoo to pure ES6, primarily the fact that ES6 classes do not (as I understand it) support some of the advanced features that Qooxdoo does; as you pointed out, interfaces is one of these features but also missing are events, and apply/transform for properties.  Personally, I think that these are *very* important and would not want to give them up.  

I can see the benefit in allowing ES6 classes to be able to inherit from Qooxdoo classes (provided that the user is prepared to loose those advanced OO ability); my thought on this have been that it would take some research to find out how to make the generated classes compatible with ES6 - I suspect that a major rewrite of the OO system would be necessary. So not impossible but not to be entered into lightly.

With regard to modules - it is possible to build Qooxdoo into one module which can be loaded via `require` or equivalent, but some of the reasons why this has not been popular is because it would be rather large (increasingly less of an issue these days perhaps), but also because the `generate.py` packages a **lot** of resources, selecting only the ones you need for your particular theme.  

Note that it's easy to produce a single module - multiple modules would depend on Qooxdoo code (and contribs and applications) knowing which class is in which module.

I think it's important to recognise that module loaders are there to overcome the shortcomings in using JS in a browser-type platform, and are affectively compromises between making code not too hard to package and load on the one hand, and breaking it up into smaller chunks that are quick to download on the other.  I do **not** think that `require` etc was created because that was the best and easiest way for a developer to work.

On the other hand, Qooxdoo's equivalent of module loading is to just take care of it all for you. As a developer, I never have to care what class is in what module, or whether that module is loaded, or what variable name that module has been assigned to in this class.  Dependency issues do not exist, and resources are always there when I use them.  It's not without compromise because you need to run a compiler stage and this is a disadvantage when it is not what people expect these days (and it makes on the fly demos hard).

> I suppose the following piecemeal approach:

I agree with those points; IMHO there is a definite use case for having a single Qooxdoo module that users can just add in and start coding with (although how resources are handled in this case I don't yet know).  Petr Kobalíček @kobalicek has worked on this in the past, with a project called qxbuild that was based on generate.py, AIUI most of the work was getting the generator to do the packaging correctly but it's something that would be easy to reimplement using the `qxcompiler` API.

(And as for outputting a qooxdoo.d.ts - that's entirely reasonable)

> @johnspackman Is it possible to for qxcompiler to transpile each qooxdoo source file from qooxdoo-lang to ES5 individually, withouth bundling referenced classes, and outputting the dependency graph of it?

Yes it does this internally already, every class file is transpiled individually and the dependency data is saved as a .json file.

> Then a simple codemod could just add import/export definitions from the dependency graph to the top of these ES5 files to make them ES6.

Don't underestimate how difficult this is - there is a difference between load-time dependencies and runtime dependencies and getting this right is non-trivial.  Are you suggesting that individual classes are loaded as modules?

> In the very long run, replace qooxdoo-lang's object orientation with >=ES6 classes, mixins and TypeScript interfaces. 

ES6 classes are not rich enough to allow this, and even if TypeScript is rich enough I would be concerned that TypeScript is not mature enough to hitch our wagon on - I think of CoffeeScript, which once seemed to be taking the world by storm but now is loosing favour and being migrated away from.

IMHO we should implement Qooxdoo to be JS based, with seamless _compatibility_ for TypeScript and ES6, plus a single-module version for those that prefer it; our support for ES6 would be by transpilation and this would expose us to the widest base of users and not bake in any requirements that may not exist (or be popular) in the future.

**Comment by johnspackman** [comment]
PS, forgot to say -

@kreimer I expect that Qooxdoo will continue support parts in the future - it's just that qxcompiler doesn't support it at the moment.  That is an area where the "does it all for you" part of dependency management gets a trickier; if modules were manually required, then @adrelino is right that parts would be obsolete because we would be switching to manual loading.  When automatically satisfying dependencies, parts would still be needed to identify code that is to be deferred in the loading process

**Comment by kreimer** [comment]
@johnspackman Would this assumption imply that some of the API (qx.io.PartLoader#require method) could be dropped? Or it would be something under the hoods, compatible and transparent for existing apps?

**Comment by johnspackman** [comment]
No - when parts are implemented, I expect that it would use the same `qx.ui.PartLoader` API so that qxcompiler is fully backwards compatible.  

However, I'm not sure how that API will work in the current implementation of `qxcompiler`-generated apps - the parts are ignored meaning that there is only one part, so the `qx.io.PartLoader.require` may fail because the part you are asking for does not exist.

**Comment by cboulanger** [comment]
It seems to me that the only purpose of the part system is to reduce load times, not to provide some kind of module system. I would keep it for backwards compatibility, and then think about what problems we want to be solving, not about what syntax we should use (that is the second thought). For example, qookery (http://www.qookery.org) does a good job loading forms and windows at run time, and solves the problem of initial load time if you like declaratively defining your UI.

**Comment by kreimer** [comment]
I confess myself a simple user of the qx part system, no dived to the generator's internal depths...  But I suspect the sophistication of its output is at least non trivial to emulate. It analyses the class dependencies of each part, and organizes them in packages with the ability of merging by size if you tell it so to do in the config... For me works perfect as it is now. I wish that future building mechanisms to generate the same outcome.  Also note that some apps not only deals with downloading UI classes but custom classes as well; and there can be lots of them.

**Comment by johnspackman** [comment]
@kreimer have you tried rebuilding you app without parts recently?  I'm curious because I don't use them, and the only benefit I think I loose is that the initial startup is a few seconds longer than it could be; literally only a couple though.  

In theory, a `build` target with one great big part won't take that much longer to download than a smaller first part - if that's true then it would mean that it is only initialisation which needs to be delayed.  Delayed *initialisation* would be much easier to implement than delayed loading.

Another thought is a small first part allows for responsive user feedback, and if there was a splash-screen facility in the loader that could go some way to making the app look really quick to load, again reducing the need for multiple parts.

**Comment by cboulanger** [comment]
For what it's worth, I use the part system to implement a plugin system with independent library classes that have their own dependencies, but also depend on qooxdoo classes (See https://demo.bibliograph.org, it has a splash screen indicating the loading of the plugins). That was not what the part system was made for, so it is kind of a hack, but cannot be realized otherwise.
Maybe a survey would be in order who uses the part system for what, and address the use cases...

**Comment by kreimer** [comment]
@johnspackman My 'boot' part represents about 50% in payload (all gzipped), the other 50% is in 10 parts (more strictly 'packages').
To prove your point (delayed initialisation vs delayed loading) all I have to do... is to pick the script of the 'boot part' and make it 'heavier' by appending spaces or comments (stuff not evaluated) up to double its size. This evening I will try this and I will tell you about the timing.
@cboulanger The splash screen looks nice, much better than my empty page... is the code available?

**Comment by cboulanger** [comment]
Here's how it works (with links to the code): the [PluginManager class](https://github.com/cboulanger/bibliograph/blob/master/bibliograph/contrib/qcl/source/class/qcl/application/PluginManager.js) is exended by the [application's PluginManager](https://github.com/cboulanger/bibliograph/blob/master/bibliograph/source/class/bibliograph/PluginManager.js), in which the plugins must be hardcoded (whether they are used or not) in order to correctly compile their dependencies and generate the parts (also in [config.json](https://github.com/cboulanger/bibliograph/blob/master/bibliograph/config.json#L70)). The [main application then loads the plugins](https://github.com/cboulanger/bibliograph/blob/master/bibliograph/source/class/bibliograph/Main.js#L399) and displays progress with the help of a [popup mixin](https://github.com/cboulanger/bibliograph/blob/master/bibliograph/contrib/qcl/source/class/qcl/ui/MLoadingPopup.js).

**Comment by hkollmann** [comment]
Obsolet with qooxdoo-compiler
