### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by Tunga37** [qooxdoo/qooxdoo#9330]
Do you know approximate date when qooxdoo 6 with MIT license will be published?
Is it matter of days, weeks, months, years? I really love qooxdoo but current license is not good enough for my goals. Maybe it's even a one of the main reasons why qooxdoo is  so underrated right know. 

I would love to use qooxdoo if I had a change but now I am afraid I will have to look for different solutions, so this question is important to me.

Best regards.

**Comment by oetiker** [comment]
If you look at the master branch, you will see that almost all of the code has already been re-licensed under MIT, there is unfortunately one contributor who has refused to re-license and it is a rather substantial bit of code ...  we have not given up hope, but since the projects of all the people actively working on qooxdoo are not impacted by it being LGPL not that much energy is going into this.

Can you elaborate in which way LGPL is hindering you in using qooxdoo for your purposes ?

**Comment by Tunga37** [comment]
Thanks for clear answer. MIT license is important, gives calmness and freedom to do what you want to do. I want to create and distribute application were one of important part is qooxdoo library with probably few changes or additions, but maybe i will be able to separate application from qooxdoo and that case LGPL will be enough.

MIT license would solve all my doubts and problems from the legal point of view and would change my approach, but it's not impossible that I will handle with what qooxdoo gives right now.

Regards.

**Comment by oetiker** [comment]
Note that LGPL means that even when you use qx in your application your application will NOT have to be LGPL ... only if you make changes to the qx source files, these changes fall under the LGPL and you have to provide the source to *YOUR CUSTOMERS* under the LGPL.

**Comment by Tunga37** [comment]
Ok, thanks for all and congratulations for your amazing work. Still, I would love to see qooxdoo under MIT, but if it is not possible right now from practical point of view, we have to deal with this. Maybe it's not as big problem as I thought before.

Regards
