### ISSUE TITLE
Changing model in VirtualComboBox while open makes wrong height

### ISSUE THREAD

**Issue by mbgonicus** [qooxdoo/qooxdoo#9362]
[Playground example](http://tinyurl.com/yastwyz9)

When a `VirtualComboBox` is opened (see #9361 why the call is deferred) and then gets its model changed, the height of the drop down is not adopted. If you close and reopen the drop down, the height is correct.

**Comment by level420** [comment]
Rhere is no recalculation of the opened list done because there is no `changeLength` listener attached to the model which can bubble up into `qx.ui.form.core.VirtualDropDownList` in order to recalculate the popup dimensions.

A solution would be to add a "changeModelLength" event to `qx.ui.list.List` which is fired if the model length changes and listen to that event in `qx.ui.form.core.VirtualDropDownList` and re-calculate the popup size by calling `qx.ui.form.core.VirtualDropDownList.__adjustSize`

**Comment by mbgonicus** [comment]
Sounds reasonable to me...

**Comment by level420** [comment]
@mbgonicus it would be great If you can offer a PR to solve this.

**Comment by mbgonicus** [comment]
I suspected that was the intention when providing the information ;) 

When I can spare a few minutes, I'll try to make a pr

**Comment by level420** [comment]
Fixed via #9370
