### ISSUE TITLE
Testrunner: test qx.test.lang.normalize.Date."test parse()" fails on current safari

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9451]
The test fails currently in line https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/test/lang/normalize/Date.js#L57 because the native `Date.parse()` on safari is able to parse dates not containing any hyphens.

It seems that current safari/webkit Date implementation does parse successfully strings like
```javascript
Date.parse("19700101")
```
into a date object.

This is exactly tested via the failing test with 
```javascript
this.assertTrue(isNaN(Date.parse("19700101")), "invalid YYYY-MM-DD (missing hyphens)");
```
There are 2 possiblitites to handle this:

1. Add a partly polyfill which overrides this behaviour so that it consistently fails on all platforms
2. Adapt the test, so it succeeds on safari but fails on all others, to be able to detect the time where either safari complies to all other browsers or the other browsers comply to safari.

I'd think that the second option is the right one, but I'm not sure.

**Comment by derrell** [comment]
From MDN:

> It is not recommended to use Date.parse as until ES5, parsing of strings was entirely implementation dependent. There are still many differences in how different hosts parse date strings, therefore date strings should be manually parsed (a library can help if many different formats are to be accommodated).

Any tests that attempt to parse, or detect that it could not parse dates are liable to fail...

**Comment by level420** [comment]
@derrell yes, but what to do with the test?

**Comment by level420** [comment]
This is part of my attempts to have the safari testrunner succeed again in order to add safari as a target via saucelabs for travis

**Comment by derrell** [comment]
@level420 Either eliminate the test, or anticipate it failing when different browsers are tested, and expect to be updating the test. We may be ok henceforth, since ES5 defines what the method should do. As long as older browsers aren't re-released with different behavior, we should continue to pass.

Since ES5 **does** define the behavior, though, to be thorough, we should probably make the tests look at the browser version, and expect exclusively the standardized behavior on modern browsers. That's more work, though...

**Comment by level420** [comment]
@derrel BTW according to https://kangax.github.io/compat-table/es5/#safari11 (not sure about the validity of the source though) claims safari to be ES5 compliant regarding the date methods.
