### ISSUE TITLE
qx.Promise misbehavior with environment setting "qx.promise" : false

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9494]
Since #9491 was merged I'm getting the following error message or warning in the console of the browser when using the generator or the compiler to generate the app with the environment setting `"qx.promise" : false`:
```
013613 qx.Promise: Promises are installed and initialised `
but disabled from properties because qx.promise==false; 
this may cause unexpected behaviour
```
One of the obvious "unexpected behaviours" I've found is that clicking on the closer icon of a window does not close the window anymore.

Would it be possible to be able to use the environment `"qx.promise" : false` again without that "unexpected behaviour"?

 I don't have any promisifyed code in my app yet and disabling promises via `qx.promise : false` gives some performance gains on the initialization of large form with lots of fields.

**Comment by level420** [comment]
It seems that the changes in https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/event/handler/DragDrop.js which now unconditional assume the availability of promises is causing the problem.

**Comment by derrell** [comment]
I think we had decided that although we were adding Promise support as an option for user applications, we would not add use of promises within the framework. We've since added promises to DragDrop. Although this seems like one of those cases of "It's easier to ask for forgiveness than to ask for permission," I'm wondering if that restriction to avoid use of promises in the framework was necessary. Do we need an option to disable promises? Is there a reason to disallow their use within the framework?

**Comment by level420** [comment]
@derrell the reason for my use case is that `qx.promise : true` has a negative performance impact in my app.

**Comment by derrell** [comment]
Interesting. In that case, we should try to find out why it's impacting performance. I think we should be able to have promise support without any degradation in performance.

**Comment by cboulanger** [comment]
Why do we need our own Promise implementation? Native promises are almost ubiquitous https://caniuse.com/#feat=promises and should be fast. For other browsers, a polyifill will do.

**Comment by level420** [comment]
@cboulanger for me IE11 is a major platform, and on IE11 the performance impact is worst.

**Comment by cboulanger** [comment]
@level420 Oh. Poor you... But not your choice, I assume.

**Comment by level420** [comment]
No, that's not my choice. A lot of the users of my apps have no choice and are forced to work even on IE11 in IE8 mode on terminal servers. Really, really bad! And even on windows 10 most users do not use edge but stay with IE11.

**Comment by johnspackman** [comment]
We use BluebirdJS promises so we can have a cross platform implementation and because they provide a series of features not available in standard promises; but it's a bug that DragDrop is requiring promises.  The event handling change I added goes to some lengths to avoid using promises unless an event handler uses it, and uses `qx.core.Environment.get("qx.promise")` to surround promise code so that it can be eliminated, I guess I forgot that in DragDrop.

**Comment by johnspackman** [comment]
@level420 Reading the comment https://github.com/qooxdoo/qooxdoo/pull/9232#issuecomment-275500094 it sounded like the performance problem @peuter reported and you diagnosed was resolved (confirmed for @peuter in https://github.com/qooxdoo/qooxdoo/pull/9232#issuecomment-275599450), and the `qx.promise` flag was only introduced to allow code reduction in the case were promises are simply not used. If you get a chance, please can you also retest your app with `qx.promise === true` and check whether there are performance (or other) issues still?
