### ISSUE TITLE
Flow layout does not re-render when no childs initially

### ISSUE THREAD

**Issue by mbgonicus** [qooxdoo/qooxdoo#9553]
In [this playground example](http://tinyurl.com/ybelbx9h) (see also below) I create a container with a flow layout and let it render. After a second, it adds a label in the then empty container.

Expectation: After the timeout, I can see the label.
Is: After the timeout, the label is invisible .

Remarks:
* In the dom, the elements are present, but the container has a height of 0.
* If you uncomment the line such that the container has a widget initially, both labels are visible as expected.
* The behaviour is identical in master and devel playground.

```js
var container = new qx.ui.container.Composite(new qx.ui.layout.Flow());
var label1 = new qx.ui.basic.Label("Label 1");
var label2 = new qx.ui.basic.Label("Label 2");

// container.add(label1);

qx.event.Timer.once(function() {
  container.add(label2);
}, null, 1000);

this.getRoot().add(container);
```

**Comment by cboulanger** [comment]
@mbgonicus Can you create a new example in the new http://www.qooxdoo.org/qxl.playground/  and see if the bug is still there?

**Comment by mbgonicus** [comment]
I don't understand, why you need a new playground. Just copy and paste the code above...

And yes, the bug still persists.

http://tinyurl.com/tsm2vdp

**Comment by johnspackman** [comment]
The issue here is that the root element has a layout of type `qx.ui.layout.Canvas`, which means that you need to give explicit positioning and dimensions when you add a widget; for example, this code works as expected:

```
this.getRoot().add(container, { top: 0, right: 0, bottom: 0, left: 0 });
```

So what's confusing is that `qx.ui.layout.Canvas` is actually zooming it out to full size - and that this only happens when there is something like a browser resize event, but it will also later reset it to zero width & height later...
