### ISSUE TITLE
New ObjectId system breaks classes that have property "owner" or "objectId", breaking backwards compatibility

### ISSUE THREAD

**Issue by milandamen** [qooxdoo/qooxdoo#9612]
**Problem 1**

The new Universal Widget ID system breaks all classes that have a property named `owner` or `objectId`. Why are these primary properties of an object? These should not be primary properties, or the new object id system should be disabled by default; because this basically breaks any application with such.

When a class of mine has a property named `owner` it will fail to define the class, because:
`Uncaught Error: Could not refine property "owner" without a "refine" flag in the property definition! This class: SomeClass, original class: qx.core.Object.`

**Reproduce**
`qx.data.marshal.Json.createModel({owner: null})`

**Problem 2**
When disabling the "module.objectid" environment, the application will crash on initialization:
`Uncaught Error: Overwriting member "_createObject" of Class "qx.core.Id" is not allowed!`

In `qx.core.Id` it is trying to overwrite the member function in `qx.core.MObjectId`.

Relevant PR: #9594

**Comment by milandamen** [comment]
@johnspackman Please look at these bugs that were introduced by the new object id system.

**Comment by johnspackman** [comment]
Looking at `module.objectid`, although I can see now why the error is occurring, it's only because `qx.core.Id` is being loaded in the first place, which should not happen.  In my quick tests here, qxcompiler does not try and load it but the generator does, even if it is not really used and that triggers the error.  As a short term solution, delete the line that reads `include: [ qx.core.MObjectId ],` from `framework/qx/core/Id.js` and recompile.

In retrospect I can see that the property name of `owner` is a poor choice however - but before I implement a change, perhaps we should discuss alternatives?

We could go for simply a longer name, such as "ownerObject" or "idOwner", or "idSystemOwner" - but ultimately these always have the potential for conflict; and as Qooxdoo has been established for some time, this **any** property name we introduce is a candidate for conflict.

It seems reasonable to think that we will from time to time introduce new properties in core systems, so IMHO we should look for a more permanent solution.  

As we already use `$` as a prefix for special, Qooxdoo-only variables, how about using that convention  going forward?  I've already done a proof of concept here and calling properties `$owner` and `$objectId` works, their accessors are called `get$objectId()` and `get$owner()`, which looks a little odd but is technically correct.

@/all Thoughts?

**Comment by hkollmann** [comment]
+1

**Comment by cboulanger** [comment]
Here are my 2 cents: 
- v6.0 is a release that can contain breaking changes.
- the id system can be turned off via the environment settings in `compile.json` (it really should be off by default for v6.0 - isn't it that way?), so it is easy to avoid breaking legacy apps. 
- Any intuitive name might collide with some legacy application, so it really doesn't matter how we name the properties, and might as well stick with the existing API. 
- prefixing by `$` is bad, since these are public properties. 

That said, we certainly do not want to make anyone's life harder if we can avoid it! Since probably nobody but me has any dependencies on the existing API, we can of course still change the name to something else. But given that @milandamen probably doesn't intend to use the id system in their apps, this seems to be not much of a problem, or is it?

**Comment by oetiker** [comment]
I would suggest to also apply some simple namespacing, that should minimize the chance for interference greatly. Lets call the properties:  `qxOwner` and `qxObjectId`. I would refrain from using the `$` sign since it is for the 'real' internal stuff that should not appear in user code.

**Comment by level420** [comment]
We could use the prefixes like `__qx__` or similar which are even more unlikely to be commonly used and document them as prefixes reserved for internal use. It might be enough to have `qx` as a prefix though. I'm here with @oetiker to not use `$` as a prefix as the property definitions are translated (afaik) internally into something also containing `$$` which then would end in having `$$$` or something similar in the code.
I'm strictly against introducing `owner` and `objectId` as qx reserved property names as suggested by @cboulanger .

**Comment by cboulanger** [comment]
Hi all, this is not an "Internal" API. It is a new API just as qx.core.Object hat all kind of other methods to work with. So ugly underscore prefixes are really not an option in my opinion. But certainly we should avoid breaking existing applications by all all means, so I am ok with a simple qx prefix to the properties.

**Comment by johnspackman** [comment]
Internally the property names are translated to `$$user_$objectId` so there is still a separation, but visually I think it's odd to have `get$objectId()` and not `get$ObjectId()` (which would not be possible to change without substantial impact, eg changing `qx.lang.String.firstUp` at the very least).

I don't want underscores because we already use them for private/protected and the same weird visual appearance of `get__qx__objectId()`.

`owner` and `objectId` really were dumb names, sorry folks :(

I'll get a new PR out with the `qx` prefix shortly...

**Comment by johnspackman** [comment]
Here's a new branch (not yet a PR) with the changes to rename the properties to `qxObjectId` and `qxOwner` - https://github.com/johnspackman/qooxdoo/tree/add-qx-prefix-to-objectid

I'll hold off creating a PR for a while to make sure everyone has a chance to contemplate this as a prefix, I'm very happy to change the names to something else but wanted to make this available as a branch somewhere so that at least anyone affected can get on straight away.

@cboulanger @milandamen in the mean time please can you both check it out and let me know of any other issues?

**Comment by milandamen** [comment]
The fix in your branch seems to work for problem 1.

As for problem 2, you can make a commit that changes the include in `qx.core.Id` to:

```
  include: qx.core.Environment.filter({
    "module.objectid" : qx.core.MObjectId
  }),
```

and it will not crash any more.

**Comment by cboulanger** [comment]
I am ok with the change - I will simply have to search/replace a few occurrences in two of my contribs once it is in master, so really no big deal!

**Comment by level420** [comment]
@johnspackman I'm fine with the `qx` prefix.

**Comment by derrell** [comment]
I'm also ok with the `qx` prefix. When I suggested prefixing with a `$` I was thinking these properties were used only internally. I agree, that would not be proper for user-visible (and user-used) properties.
